/**
 * Hardcoded product data used when the database is unavailable.
 * Both the shop listing and product detail pages fall back to this data.
 */

export interface FallbackProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  priceCents: number;
  compareAtPriceCents: number | null;
  stripePriceId: string;
  blobUrl: string;
  imageUrl: string | null;
  previewFile: string | null;
  category: string;
  isBundle: boolean;
  bundleProductIds: string | null;
  activityCount: number | null;
  ageRange: string | null;
  sortOrder: number;
  active: boolean;
  createdAt: Date;
}

// ─── Price tiers: Tier 1 $4.99 (singles) · Tier 2 $6.99 (nature card packs) · Tier 3 $12.99 (seasonal packs) · Tier 4 $9.99 (comprehensive guides) ───
// Bundle compareAt = sum of individual prices at current tiers

export const fallbackProducts: FallbackProduct[] = [
  // ─────────────────────────────────────────────────────────────
  // BUNDLES
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-seasonal-bundle",
    name: "Full Seasonal Bundle",
    slug: "seasonal-bundle",
    description:
      "All four seasonal packs in one download: spring, summer, autumn, and winter. 80 outdoor activities designed to match each season's unique energy and opportunities. From spring planting and bird-watching to winter star-gazing and ice experiments. Your family gets a full year of outdoor learning, ready to use whenever the season changes.",
    shortDescription:
      "All 4 seasonal packs, 80 outdoor activities for every time of year.",
    priceCents: 4499,
    compareAtPriceCents: 5999,
    stripePriceId: "price_1TFcTNAMzOBftCntknn9ugHW",
    blobUrl: "",
    imageUrl: "/products/four-seasons-bundle.jpg",
    previewFile: "Preview 4 seasons bundle.pdf",
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 80,
    ageRange: "Ages 6–14",
    sortOrder: 1,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-creativity-mega-bundle",
    name: "Creativity & Imagination Mega Bundle",
    slug: "creativity-mega-bundle",
    description:
      "All 10 Creativity Anywhere projects in one download. From building board games and Rube Goldberg machines to creating theme parks, museums, and stop-motion films. Each project is a multi-step creative adventure that builds design thinking, problem-solving, and artistic confidence. 10 complete projects, low prep required.",
    shortDescription:
      "All 10 Creativity Anywhere projects: design, build, and create without limits.",
    priceCents: 4499,
    compareAtPriceCents: 5999,
    stripePriceId: "price_1TFcTNAMzOBftCntDc8CoKsa",
    blobUrl: "",
    imageUrl: "/products/mega-bundle-creativity.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 6–14",
    sortOrder: 2,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-real-world-mega-bundle",
    name: "Real-World Relevance Mega Bundle",
    slug: "real-world-mega-bundle",
    description:
      "All 10 Real-World Relevance challenges in one download. Budgeting, meal planning, micro-businesses, media literacy, travel planning, smart shopping, and more. Each challenge puts kids in real-life scenarios where they practise the skills that actually matter: critical thinking, financial literacy, communication, and problem-solving.",
    shortDescription:
      "All 10 Real-World Relevance challenges: life skills, financial literacy, and project-based learning.",
    priceCents: 4499,
    compareAtPriceCents: 5999,
    stripePriceId: "price_1TFcTNAMzOBftCntZTSpWFfb",
    blobUrl: "",
    imageUrl: "/products/mega-bundle-real-world.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 9–14",
    sortOrder: 3,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-ai-digital-bundle",
    name: "AI & Digital Literacy Bundle",
    slug: "ai-digital-bundle",
    description:
      "All 10 AI & Digital Literacy activities in one download. From understanding what AI actually is, to spotting deepfakes, checking for bias, building ethical AI projects, and managing digital boundaries. Each activity is designed for ages 9–14 and helps kids become critical, confident, and responsible digital citizens.",
    shortDescription:
      "All 10 AI & Digital Literacy activities: responsible tech, critical thinking, and digital citizenship.",
    priceCents: 4499,
    compareAtPriceCents: 5999,
    stripePriceId: "price_1TFcTOAMzOBftCntHzTASW76",
    blobUrl: "",
    imageUrl: "/products/mega-bundle-ai-digital.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 9–14",
    sortOrder: 4,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-real-world-math-bundle",
    name: "Real-World Math Mega Bundle",
    slug: "real-world-math-bundle",
    description:
      "All 10 Real-World Math guides in one download: backyard campouts, garage sales, garden plots, road trips, sports stats, and more. Every activity puts kids in real-life scenarios where they use maths to plan, budget, measure, and make smart decisions. The kind of maths that actually sticks because it actually matters.",
    shortDescription:
      "All 10 Real-World Math guides: budgeting, planning, and problem-solving with real numbers.",
    priceCents: 4499,
    compareAtPriceCents: 5999,
    stripePriceId: "price_1TFcTOAMzOBftCntWV4GZeM4",
    blobUrl: "",
    imageUrl: "/products/mega-bundle-real-world-math.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 6–14",
    sortOrder: 8,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-nature-art-bundle",
    name: "Nature Art Bundle",
    slug: "nature-art-bundle",
    description:
      "Three of our most popular nature packs together: Land Art Challenge Cards, Nature Crafts for Kids, and the Nature Journal. From building sculptures with sticks and stones to pressing flowers, sketching wildlife, and creating nature mandalas. Everything your family needs to turn the outdoors into an art studio.",
    shortDescription:
      "Land Art + Nature Crafts + Nature Journal. Turn the outdoors into an art studio.",
    priceCents: 1799,
    compareAtPriceCents: 2397,
    stripePriceId: "price_1TFcTPAMzOBftCntIs6rjc1V",
    blobUrl: "",
    imageUrl: "/products/nature-art-bundle.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 5,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-outdoor-toolkit-bundle",
    name: "Outdoor Learning Toolkit Bundle",
    slug: "outdoor-toolkit-bundle",
    description:
      "Four essential outdoor learning packs in one download: Nature Walk Task Cards, Outdoor Learning Missions, STEM Challenge Cards, and Nature Choice Boards. Whether you're in the backyard, at the park, or on a trail, these cards give your kids a reason to explore, observe, test, and discover. Low prep, maximum outdoor time.",
    shortDescription:
      "Nature Walk Cards + Missions + STEM Challenges + Choice Boards, your complete outdoor toolkit.",
    priceCents: 2399,
    compareAtPriceCents: 3196,
    stripePriceId: "price_1TFcTPAMzOBftCntA7iWyJ5t",
    blobUrl: "",
    imageUrl: "/products/outdoor-toolkit-bundle.jpg",
    previewFile: "Preview Toolkit bundle.pdf",
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 6,
    active: true,
    createdAt: new Date("2025-02-01"),
  },

  {
    id: "fb-outdoor-mega-bundle",
    name: "Outdoor & Nature Mega Bundle",
    slug: "outdoor-mega-bundle",
    description:
      "All 7 outdoor and nature activity guides in one download: Nature Walk Task Cards, Outdoor Learning Missions, STEM Challenge Cards, Nature Choice Boards, Land Art Challenges, Nature Crafts, and My Nature Journal. The complete outdoor toolkit for families who learn outside.",
    shortDescription:
      "All 7 outdoor & nature packs in one download.",
    priceCents: 4199,
    compareAtPriceCents: 5593,
    stripePriceId: "price_1TIVzrAMzOBftCntORiPbt2P",
    blobUrl: "",
    imageUrl: "/products/mega-bundle-outdoor.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 8,
    active: true,
    createdAt: new Date("2025-02-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // NATURE - Seasonal packs (merged into Nature)
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-spring-outdoor",
    name: "Spring Outdoor Learning Pack",
    slug: "spring-outdoor-pack",
    description:
      "20 outdoor activities that use spring's energy to build real-world skills. Plant a seed and track its growth. Build a bug hotel. Create a rain gauge from a jar. Map the birds in your garden. Every activity connects to science, maths, or literacy, but feels like adventure, not homework.",
    shortDescription:
      "20 outdoor activities that use spring's energy to build real-world skills.",
    priceCents: 1499,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTQAMzOBftCntYvoO0bs3",
    blobUrl: "",
    imageUrl: "/products/spring-outdoor-pack.jpg",
    previewFile: "Preview Anywhere Learning Spring.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 6–14",
    sortOrder: 10,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-summer-outdoor",
    name: "Summer Outdoor Learning Pack",
    slug: "summer-outdoor-pack",
    description:
      "20 summer activities for families who learn on the move. Water experiments, shadow tracking, outdoor cooking, beach science, and more. Designed for long sunny days when kids have energy to burn and curiosity to spare.",
    shortDescription:
      "20 summer activities: water experiments, outdoor cooking, and sun-powered learning.",
    priceCents: 1499,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTRAMzOBftCntcBe5IbiX",
    blobUrl: "",
    imageUrl: "/products/summer-outdoor-pack.jpg",
    previewFile: "Preview Anywhere Learning Summer.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 6–14",
    sortOrder: 11,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-fall-outdoor",
    name: "Fall Outdoor Learning Pack",
    slug: "fall-outdoor-pack",
    description:
      "20 autumn activities that use the changing season to build observation and creative skills. Leaf collecting, weather tracking, nature journaling, harvest maths, and more. Perfect for families who want to make the most of shorter days and golden light.",
    shortDescription:
      "20 autumn activities: leaf science, harvest maths, and seasonal observation.",
    priceCents: 1499,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTRAMzOBftCntOiiukmBd",
    blobUrl: "",
    imageUrl: "/products/fall-outdoor-pack.jpg",
    previewFile: "Preview Anywhere Learning Fall.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 6–14",
    sortOrder: 12,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-winter-outdoor",
    name: "Winter Outdoor Learning Pack",
    slug: "winter-outdoor-pack",
    description:
      "20 winter activities for cosy indoor days and cold outdoor adventures. Ice experiments, star-gazing, shadow play, winter bird feeding, and fireside storytelling. Designed for families who want to keep learning alive even when the weather says stay inside.",
    shortDescription:
      "20 winter activities: ice experiments, star-gazing, and cosy indoor learning.",
    priceCents: 1499,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTSAMzOBftCntqOOGzx0P",
    blobUrl: "",
    imageUrl: "/products/winter-outdoor-pack.jpg",
    previewFile: "Preview Anywhere Learning Winter.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 6–14",
    sortOrder: 13,
    active: true,
    createdAt: new Date("2025-02-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // NATURE
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-nature-journal",
    name: "My Nature Journal",
    slug: "nature-journal-walks",
    description:
      "A guided nature journal that helps kids slow down, observe, and connect with the outdoors. Packed with prompts for sketching, writing, and recording what they see, hear, and wonder about. Works in any season, any landscape — backyard, park, trail, or beach. No nature expertise required from you. Just open it up, step outside, and let curiosity lead.",
    shortDescription:
      "A guided nature journal with prompts for sketching, writing, and outdoor observation.",
    priceCents: 799,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTSAMzOBftCntNAM1nnp4",
    blobUrl: "",
    imageUrl: "/products/nature-journal-walks.jpg",
    previewFile: "Preview My nature journal.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 20,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-nature-walk-tasks",
    name: "Nature Walk Task Cards",
    slug: "nature-walk-task-cards",
    description:
      "Task cards that turn any walk into a focused nature exploration. Each card gives kids a specific mission: find three textures, listen for five sounds, sketch the smallest thing you can find. Works in any outdoor space, any season, any weather.",
    shortDescription:
      "Task cards that turn any walk into a focused nature exploration.",
    priceCents: 799,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTTAMzOBftCnt7T0mraep",
    blobUrl: "",
    imageUrl: "/products/nature-walk-task-cards.jpg",
    previewFile: "Preview Nature Walk Task Cards.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 21,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-nature-choice-boards",
    name: "Nature Choice Boards",
    slug: "nature-choice-boards",
    description:
      "Choose-your-own-adventure style nature activities. Each board gives kids 9 options to pick from: observe, create, explore, or investigate. Perfect for self-directed learners who want to choose what to do outside. Works in backyards, parks, forests, and beaches.",
    shortDescription:
      "Choose-your-own-adventure nature activities with 9 options per board for self-directed outdoor learning.",
    priceCents: 799,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTTAMzOBftCntVkFfPzek",
    blobUrl: "",
    imageUrl: "/products/nature-choice-boards.jpg",
    previewFile: "Preview Nature Choice Boards.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 22,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-outdoor-missions",
    name: "Outdoor Learning Missions",
    slug: "outdoor-learning-missions",
    description:
      "Mission-style outdoor challenges that get kids moving, observing, and problem-solving in nature. Each mission has a clear objective, steps to follow, and a reflection prompt. From building shelters to mapping wildlife trails, these are real adventures that feel important.",
    shortDescription:
      "Mission-style outdoor challenges: build, explore, observe, and problem-solve in nature.",
    priceCents: 799,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTUAMzOBftCntCKLS3VQS",
    blobUrl: "",
    imageUrl: "/products/outdoor-learning-missions.jpg",
    previewFile: "Preview Outdoor learning missions.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 23,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-outdoor-stem",
    name: "Outdoor STEM Challenge Cards",
    slug: "outdoor-stem-challenges",
    description:
      "20 outdoor STEM challenges that use the natural world as a laboratory. Build a bridge from sticks. Design a waterproof shelter. Measure tree heights using shadows. Engineer a boat that floats. Each challenge has constraints that force creative problem-solving with no instructions, just goals.",
    shortDescription:
      "20 outdoor STEM challenges: build, test, and engineer using what nature provides.",
    priceCents: 799,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTUAMzOBftCntt5p1Oosa",
    blobUrl: "",
    imageUrl: "/products/outdoor-stem-challenges.jpg",
    previewFile: "Preview Outdoor STEM Challenge Cards.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 6–14",
    sortOrder: 24,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-land-art",
    name: "Land Art Challenge Cards",
    slug: "land-art-challenges",
    description:
      "15 land art challenges that turn natural materials into beautiful, temporary art. Create a mandala from stones. Build a spiral from leaves. Arrange colours from the forest floor. Kids learn about patterns, symmetry, and design, all while being creative outdoors with zero mess to clean up.",
    shortDescription:
      "15 land art challenges: create beautiful, temporary art using natural materials.",
    priceCents: 799,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTUAMzOBftCntKXDbLWvQ",
    blobUrl: "",
    imageUrl: "/products/land-art-challenges.jpg",
    previewFile: "Preview Land Art Challenge Cards.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 15,
    ageRange: "Ages 6–14",
    sortOrder: 25,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-nature-crafts",
    name: "Nature Crafts for Kids",
    slug: "nature-crafts",
    description:
      "Hands-on nature craft projects using materials found outdoors. Leaf pressing, stick weaving, flower pounding, bark rubbings, and more. Each project connects creativity with nature observation. Kids collect materials, then create something beautiful with what they find.",
    shortDescription:
      "Hands-on nature craft projects using materials found outdoors.",
    priceCents: 799,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTVAMzOBftCntMzWbHkjq",
    blobUrl: "",
    imageUrl: "/products/nature-crafts.jpg",
    previewFile: "Preview Nature crafts for kids.pdf",
    category: "outdoor-learning",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 26,
    active: true,
    createdAt: new Date("2025-02-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // CREATIVITY
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-board-game-studio",
    name: "Board Game Studio",
    slug: "board-game-studio",
    description:
      "Design, build, and playtest an original board game from scratch. Kids brainstorm themes, create rules, design the board, craft game pieces, and iterate based on playtesting. A complete creative project that builds design thinking, strategic reasoning, and communication skills.",
    shortDescription:
      "Design, build, and playtest an original board game from scratch.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTWAMzOBftCntCEdcAPUE",
    blobUrl: "",
    imageUrl: "/products/board-game-studio.jpg",
    previewFile: "Preview Creativity anywhere Board game studio.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 31,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-rube-goldberg",
    name: "Build a Rube Goldberg Machine",
    slug: "rube-goldberg-machine",
    description:
      "Build an absurdly complicated machine to do something simple. Kids design chain reactions using everyday materials: dominoes, ramps, balls, levers. Each step teaches engineering principles, cause-and-effect thinking, and creative problem-solving. Failure is part of the fun.",
    shortDescription:
      "Build an absurdly complicated machine to do something simple. Engineering meets creativity.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTWAMzOBftCnt2HICs5Uj",
    blobUrl: "",
    imageUrl: "/products/rube-goldberg-machine.jpg",
    previewFile: "Preview Creativity anywhere Build a Rube Goldberg Machine.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 32,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-survival-base",
    name: "Build a Survival Base",
    slug: "survival-base",
    description:
      "Design and build a survival base for an imaginary expedition. Kids choose a biome, research challenges, plan their base layout, create models, and present their design. Combines geography, engineering, creative writing, and problem-solving in one immersive project.",
    shortDescription:
      "Design a survival base for an imaginary expedition. Geography meets engineering.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTXAMzOBftCnt2xp5XUtF",
    blobUrl: "",
    imageUrl: "/products/survival-base.jpg",
    previewFile: "Preview Creativity anywhere Build a Survival Base for an Imaginary Expedition.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 33,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-imaginary-world",
    name: "Build an Imaginary World",
    slug: "imaginary-world",
    description:
      "Create an entire imaginary world from scratch, including its geography, creatures, rules, languages, and stories. Kids build maps, design ecosystems, invent civilisations, and write lore. A massive open-ended creative project that can last days or weeks.",
    shortDescription:
      "Create an entire imaginary world: geography, creatures, rules, and stories.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTXAMzOBftCntLpxVnTiV",
    blobUrl: "",
    imageUrl: "/products/imaginary-world.jpg",
    previewFile: "Preview Creativity anywhere Build an imaginary world.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 34,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-creature-habitat",
    name: "Create a Creature + Build Its Habitat",
    slug: "creature-habitat",
    description:
      "Invent a brand-new creature and build its entire habitat. Kids design anatomy, diet, behaviour, and environment. Then they construct a physical model of the habitat. Combines biology, art, engineering, and creative writing in one unforgettable project.",
    shortDescription:
      "Invent a creature and build its habitat. Biology meets art and engineering.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTXAMzOBftCntW0sHBYh3",
    blobUrl: "",
    imageUrl: "/products/creature-habitat.jpg",
    previewFile: "Preview Creativity anywhere Create a Creature + Build Its Habitat.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 35,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-theme-park",
    name: "Create a Theme Park or Adventure Course",
    slug: "theme-park",
    description:
      "Design a theme park or adventure course from concept to completion. Kids plan rides, map layouts, calculate budgets, design marketing materials, and build scale models. A project that combines maths, art, engineering, and business thinking.",
    shortDescription:
      "Design a theme park: plan rides, map layouts, and build scale models.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTYAMzOBftCntmrRvbNvV",
    blobUrl: "",
    imageUrl: "/products/theme-park.jpg",
    previewFile: "Preview Creativity anywhere Create a Theme Park or Adventure Course.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 36,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-mini-movie",
    name: "Create a Mini Movie or Radio Drama",
    slug: "mini-movie",
    description:
      "Create a mini movie, stop-motion animation, or radio drama from scratch. Kids write scripts, design sets, create characters, record audio, and edit their production. A full creative process from concept to premiere. No fancy equipment needed, just a phone and imagination.",
    shortDescription:
      "Create a mini movie, stop-motion, or radio drama, from script to premiere.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTYAMzOBftCntIDZw27XK",
    blobUrl: "",
    imageUrl: "/products/mini-movie.jpg",
    previewFile: "Preview Creativity anywhere Create a mini movie,  stop-motion or radio drama.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 37,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-invent-sport",
    name: "Invent a New Sport",
    slug: "invent-a-sport",
    description:
      "Create an entirely new sport with original rules, equipment, and scoring. Kids design the game, build equipment from everyday materials, write a rulebook, playtest with family, and iterate. A masterclass in creative thinking, negotiation, and physical activity.",
    shortDescription:
      "Create an entirely new sport: design rules, build equipment, and playtest.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTZAMzOBftCntKUnaOIk2",
    blobUrl: "",
    imageUrl: "/products/invent-a-sport.jpg",
    previewFile: "Preview Creativity anywhere Invent a new sport.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 38,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-kinetic-sculpture",
    name: "Kinetic Sculpture or Art Installation",
    slug: "kinetic-sculpture",
    description:
      "Design and build a kinetic sculpture or interactive art installation. Kids explore movement, balance, wind, and gravity to create art that moves. Combines physics, engineering, and artistic expression in a hands-on project that produces something genuinely impressive.",
    shortDescription:
      "Build a kinetic sculpture: art that moves using physics and engineering.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTZAMzOBftCntETLFEzEA",
    blobUrl: "",
    imageUrl: "/products/kinetic-sculpture.jpg",
    previewFile: "Preview Creativity anywhere Kinetic Sculpture or Art Installation.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 39,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-build-museum",
    name: "Build a Museum or Interactive Exhibit",
    slug: "build-a-museum",
    description:
      "Create a museum or interactive exhibit on any topic your child loves. Research, curate, design displays, write labels, build interactive elements, and host a grand opening. A project that teaches research, writing, presentation, and design, all driven by your child's own interests.",
    shortDescription:
      "Create a museum exhibit: research, curate, design, and host a grand opening.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTaAMzOBftCntswLeOkPC",
    blobUrl: "",
    imageUrl: "/products/build-a-museum.jpg",
    previewFile: "Preview Creativity anywhere build a museum or interactive exhibit.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 40,
    active: true,
    createdAt: new Date("2025-02-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // REAL-WORLD MATH, CRITICAL THINKING, SELF-MANAGEMENT & LITERACY
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-budget-challenge",
    name: "Real-Life Budget Challenge",
    slug: "budget-challenge",
    description:
      "Real-money challenges that teach kids budgeting and smart spending. Kids plan a meal on a budget, track family spending for a week, compare prices at different shops, and design their own savings plan. Financial literacy through real-world practice, low prep needed.",
    shortDescription:
      "Real-money challenges that teach kids budgeting, saving, and smart spending.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTaAMzOBftCntcx3BoyC8",
    blobUrl: "",
    imageUrl: "/products/budget-challenge.jpg",
    previewFile: "Preview Real-world relevance Budget challenge.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 110,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-community-impact",
    name: "Community Impact Project",
    slug: "community-impact",
    description:
      "Guide your child through planning and executing a real community impact project. From identifying local needs to designing solutions, creating action plans, and reflecting on results. Builds empathy, planning skills, and a sense of civic responsibility.",
    shortDescription:
      "Plan and execute a real community impact project. Empathy in action.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTbAMzOBftCntFStp6niy",
    blobUrl: "",
    imageUrl: "/products/community-impact.jpg",
    previewFile: "Preview Real-world relevance Community impact project.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 140,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-kitchen-math",
    name: "Kitchen Math & Meal Planning Challenge",
    slug: "kitchen-math-challenge",
    description:
      "Go beyond recipes. Plan meals for a week, calculate grocery costs, compare unit prices, adjust portions, and manage a food budget. Real-world maths that happens in the kitchen, at the shop, and around the dinner table.",
    shortDescription:
      "Plan meals, calculate costs, and manage a food budget. Real-world kitchen maths.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTbAMzOBftCntCTnW0gph",
    blobUrl: "",
    imageUrl: "/products/kitchen-math-challenge.jpg",
    previewFile: "Preview Real-world relevance Kitchen math & meal planning challenge.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 111,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-media-info-check",
    name: "Media & Info Check",
    slug: "media-info-check",
    description:
      "Critical thinking activities that teach kids to evaluate information, spot bias, check sources, and think critically about what they see online. In a world of misinformation, these are essential skills, and they're best learned through practice, not lectures.",
    shortDescription:
      "Critical thinking activities: evaluate sources, spot bias, and check facts.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTcAMzOBftCntRkLHGW3w",
    blobUrl: "",
    imageUrl: "/products/media-info-check.jpg",
    previewFile: "Preview Real-world relevance Media & info check.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 80,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-micro-business",
    name: "Micro-Business Challenge",
    slug: "micro-business",
    description:
      "Guided activities to help your child plan, launch, and run a simple real business. From choosing a product to setting prices, marketing, tracking income, and reflecting on what they learned. Entrepreneurship skills through hands-on experience.",
    shortDescription:
      "Plan, launch, and run a real micro-business. Entrepreneurship for kids.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTcAMzOBftCntZcUkdoFu",
    blobUrl: "",
    imageUrl: "/products/micro-business.jpg",
    previewFile: "Preview Real-world relevance Micro-business challenge.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 130,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-problem-solver",
    name: "Problem-Solver Studio",
    slug: "problem-solver",
    description:
      "Design thinking challenges that teach kids to identify problems, brainstorm solutions, prototype, test, and iterate. Real-world problem-solving skills applied to everyday life, from improving a family routine to designing a better lunchbox.",
    shortDescription:
      "Design thinking challenges: identify problems, brainstorm, prototype, and iterate.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTcAMzOBftCntgT52Nlxh",
    blobUrl: "",
    imageUrl: "/products/problem-solver.jpg",
    previewFile: "Preview Real-world relevance Problem-solver studio.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 141,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-smart-shopper",
    name: "Smart Shopper Lab",
    slug: "smart-shopper",
    description:
      "Activities that teach kids to be critical, informed consumers. Compare prices, read labels, spot marketing tricks, calculate value, and make smart purchasing decisions. Financial literacy meets critical thinking. Skills they'll use for life.",
    shortDescription:
      "Learn to compare prices, read labels, and make smart purchasing decisions.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTdAMzOBftCntoJjP3hy7",
    blobUrl: "",
    imageUrl: "/products/smart-shopper.jpg",
    previewFile: "Preview Real-world relevance Smart shopper lab.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 112,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-time-energy-planner",
    name: "Time & Energy Planner",
    slug: "time-energy-planner",
    description:
      "Help your child learn to manage their time and energy effectively. Activities include building weekly schedules, tracking energy levels, prioritising tasks, setting goals, and reflecting on what works. Self-management skills that schools rarely teach.",
    shortDescription:
      "Build schedules, track energy, and learn self-management. Essential life skills.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTdAMzOBftCntcxl1ggJF",
    blobUrl: "",
    imageUrl: "/products/time-energy-planner.jpg",
    previewFile: "Preview Real-world relevance Time & energy planner.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 142,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-travel-day",
    name: "Travel Day Itinerary Challenge",
    slug: "travel-day",
    description:
      "Challenge your child to plan a real travel day from start to finish. Research destinations, compare transport options, calculate budgets, build itineraries, and navigate logistics. Geography, maths, and decision-making wrapped in an exciting real-world project.",
    shortDescription:
      "Plan a real travel day: research, budget, and build a complete itinerary.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTeAMzOBftCntm89oK6q4",
    blobUrl: "",
    imageUrl: "/products/travel-day.jpg",
    previewFile: "Preview Real-world relevance Travel Day itinerary challenge.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 143,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-write-like-pro",
    name: "Write It Like a Pro",
    slug: "write-like-a-pro",
    description:
      "Real-world writing challenges that go beyond essays. Kids write emails, create social media posts, draft persuasive letters, design infographics with captions, and communicate for real audiences. Writing skills that matter in the real world, practised in context.",
    shortDescription:
      "Real-world writing challenges: emails, letters, persuasive writing, and communication.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTeAMzOBftCnti098zzDn",
    blobUrl: "",
    imageUrl: "/products/write-like-a-pro.jpg",
    previewFile: "Preview Real-world relevance Write it like a pro.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 120,
    active: true,
    createdAt: new Date("2025-04-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // AI & DIGITAL LITERACY
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-ai-basics",
    name: "AI Basics: Myths, Facts & Smart Rules",
    slug: "ai-basics",
    description:
      "Help kids understand what AI actually is, what it isn't, and how to use it responsibly. Activities cover how AI works, common myths vs reality, healthy and useful AI interactions, and setting smart rules for AI use at home. The foundation for everything else in the AI series.",
    shortDescription:
      "What AI actually is, common myths vs facts, and smart rules for responsible use.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTfAMzOBftCntjVdNUY97",
    blobUrl: "",
    imageUrl: "/products/ai-basics.jpg",
    previewFile: "Preview AI + Digital Literacy - AI BASICS MYTHS, FACTS & SMART RULES.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 70,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-algorithm-awareness",
    name: "Algorithm Awareness: Why Am I Seeing This?",
    slug: "algorithm-awareness",
    description:
      "Teach kids how algorithms shape what they see online, and what they don't. Activities explore recommendation systems, filter bubbles, engagement tricks, and how to take back control of their feed. Critical digital literacy for the attention economy.",
    shortDescription:
      "Understand how algorithms shape what you see online, and take back control.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTfAMzOBftCntwgbhXS2c",
    blobUrl: "",
    imageUrl: "/products/algorithm-awareness.jpg",
    previewFile: "Preview AI + Digital Literacy - ALGORITHM AWARENESS WHY AM I SEEING THIS.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 71,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-bias-fairness",
    name: "Bias & Fairness Lab",
    slug: "bias-fairness-lab",
    description:
      "Explore how AI can be unfair, and what to do about it. Kids investigate real examples of AI bias, examine who gets left out, test for fairness in prompts and outputs, and design better AI choices. Ethics and critical thinking through hands-on investigation.",
    shortDescription:
      "Investigate AI bias: who gets left out, why, and how to design for fairness.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTgAMzOBftCnty4weOSMp",
    blobUrl: "",
    imageUrl: "/products/bias-fairness-lab.jpg",
    previewFile: "Preview AI + Digital Literacy - BIAS & FAIRNESS LAB.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 72,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-build-ai-helper",
    name: "Build Your Own AI Helper",
    slug: "build-ai-helper",
    description:
      "Design and plan your own AI helper: what it does, how it works, what data it needs, and what ethical rules it follows. Kids think through the entire process of creating a useful AI tool, from concept to safety considerations. No coding required; this is about thinking, not programming.",
    shortDescription:
      "Design an AI helper from concept to ethics. Creative tech thinking, no coding needed.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTgAMzOBftCnt2rlB7hz4",
    blobUrl: "",
    imageUrl: "/products/build-ai-helper.jpg",
    previewFile: "Preview AI + Digital Literacy - BUILD YOUR OWN AI HELPER.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 73,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-create-with-ai",
    name: "Create With AI, Ethically",
    slug: "create-with-ai",
    description:
      "Explore creative AI tools responsibly. Kids learn to use AI for writing, art, and brainstorming while understanding copyright, attribution, and the difference between using AI as a tool vs letting it do the thinking. Creativity enhanced by technology, guided by ethics.",
    shortDescription:
      "Use AI for creative projects responsibly: copyright, attribution, and ethical creation.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcThAMzOBftCnt9kE7d4xI",
    blobUrl: "",
    imageUrl: "/products/create-with-ai.jpg",
    previewFile: "Preview AI + Digital Literacy - CREATE WITH AI, ETHICALLY.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 74,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-deepfake-spotter",
    name: "Deepfake & Manipulation Spotter",
    slug: "deepfake-spotter",
    description:
      "Teach kids to spot manipulated images, videos, and content. Activities cover deepfake detection, image verification, \"pause before sharing\" skills, and how to evaluate whether what they're seeing is real. Essential media literacy for the AI age.",
    shortDescription:
      "Spot deepfakes and manipulated content. Essential media literacy for the AI age.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcThAMzOBftCntXZfm3eqs",
    blobUrl: "",
    imageUrl: "/products/deepfake-spotter.jpg",
    previewFile: "Preview AI + Digital Literacy - DEEPFAKE & MANIPULATION SPOTTER.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 75,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-hallucination-detective",
    name: "Hallucination Detective",
    slug: "hallucination-detective",
    description:
      "Investigation activities that teach kids to spot when AI gets things wrong. Kids learn about AI hallucinations, practise verifying AI outputs, understand why AI makes confident mistakes, and develop the habit of always checking before trusting. Trust, verify, and improve.",
    shortDescription:
      "Spot when AI gets things wrong. Verify, fact-check, and build critical trust.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcThAMzOBftCnthpXo1GG3",
    blobUrl: "",
    imageUrl: "/products/hallucination-detective.jpg",
    previewFile: "Preview AI + Digital Literacy - HALLUCINATION DETECTIVE.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 76,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-healthy-tech",
    name: "Healthy Tech & AI Boundaries Plan",
    slug: "healthy-tech-boundaries",
    description:
      "Help your child create a personal technology and AI boundaries plan. Activities cover screen time awareness, digital wellbeing, setting healthy limits, managing notifications, and building a balanced relationship with technology. Self-regulation skills for the digital age.",
    shortDescription:
      "Create a personal tech boundaries plan for digital wellbeing and self-regulation.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTiAMzOBftCntLgtp68hD",
    blobUrl: "",
    imageUrl: "/products/healthy-tech-boundaries.jpg",
    previewFile: "Preview AI + Digital Literacy - HEALTHY TECH & AI BOUNDARIES PLAN.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 77,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-privacy-footprint",
    name: "Privacy & Digital Footprint Map",
    slug: "privacy-footprint",
    description:
      "Map your digital footprint and understand online privacy. Kids discover what personal data they share, how data trails work, smart sharing practices, and how to protect their personal information. Practical privacy education, not paranoia.",
    shortDescription:
      "Map your digital footprint: understand data, privacy, and smart sharing.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTiAMzOBftCntrpKs7RZt",
    blobUrl: "",
    imageUrl: "/products/privacy-footprint.jpg",
    previewFile: "Preview AI + Digital Literacy - PRIVACY & DIGITAL FOOTPRINT MAP.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 78,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-prompt-coach",
    name: "Prompt Like a Coach",
    slug: "prompt-like-a-coach",
    description:
      "Teach kids to get better results from AI by writing better prompts. Activities cover prompt structure, asking better questions, healthy AI use (not copying), and learning to guide AI rather than just accepting its first answer. The skill that makes all other AI skills more powerful.",
    shortDescription:
      "Write better AI prompts: ask better questions and guide AI like a coach.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTjAMzOBftCntIAAq45jj",
    blobUrl: "",
    imageUrl: "/products/prompt-like-a-coach.jpg",
    previewFile: "Preview AI + Digital Literacy - PROMPT LIKE A COACH.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 79,
    active: true,
    createdAt: new Date("2025-03-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // REAL-WORLD MATH - New guides
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-backyard-campout-planner",
    name: "Backyard Campout Planner",
    slug: "backyard-campout-planner",
    description:
      "Plan a backyard campout from start to finish: gear lists, meal prep, a stargazing schedule, and a campfire activity plan. Kids use measurement, budgeting, time planning, and estimation to organise a real overnight adventure. Maths that ends with marshmallows.",
    shortDescription:
      "Plan a backyard campout with real maths: gear, meals, stargazing, and budgets.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTjAMzOBftCntwUjIM1oY",
    blobUrl: "",
    imageUrl: "/products/backyard-campout-planner.jpg",
    previewFile: "Preview Real-world math - Backyard Campout Planner.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 100,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-clothing-swap-thrift-math",
    name: "Clothing Swap & Thrift Math",
    slug: "clothing-swap-thrift-math",
    description:
      "Organise a clothing swap or plan a thrift store haul using real budgeting and value skills. Kids calculate cost-per-wear, compare prices, assess quality, and make smart spending decisions. Financial literacy meets sustainability. Maths with purpose.",
    shortDescription:
      "Thrift shopping and clothing swap maths: budgets, value, and smart spending.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTkAMzOBftCntI5TYd61b",
    blobUrl: "",
    imageUrl: "/products/clothing-swap-thrift-math.jpg",
    previewFile: "Preview Real-world math - Clothing Swap & Thrift Math.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 101,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-family-electricity-audit",
    name: "Family Electricity Audit",
    slug: "family-electricity-audit",
    description:
      "Audit your household electricity use, read meters, calculate costs, compare appliances, and find real ways to save. Kids learn about kilowatt-hours, unit pricing, and the maths behind energy bills. Practical environmental maths that makes a real difference at home.",
    shortDescription:
      "Audit electricity use, calculate costs, and find real ways to save.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTkAMzOBftCntqGIpYdvv",
    blobUrl: "",
    imageUrl: "/products/family-electricity-audit.jpg",
    previewFile: "Preview Real-world math - Family Electricity Audit.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 102,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-farmers-market-challenge",
    name: "Farmers Market Challenge",
    slug: "farmers-market-challenge",
    description:
      "Navigate a farmers market with a real budget. Compare prices, weigh options, calculate change, and make smart choices. Kids practise mental maths, estimation, and decision-making while shopping for real food. The kind of maths lesson that ends with a great meal.",
    shortDescription:
      "Budget and shop at a farmers market: prices, change, and smart choices.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTlAMzOBftCntP7s0G52o",
    blobUrl: "",
    imageUrl: "/products/farmers-market-challenge.jpg",
    previewFile: "Preview Real-world math - Farmers Market Challenge.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 103,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-garage-sale-math",
    name: "Garage Sale Math",
    slug: "garage-sale-math",
    description:
      "Plan, price, and run a garage sale using real-world maths and money skills. Kids sort items, research prices, create price tags, make change, and track earnings. Addition, subtraction, multiplication, percentages, and money handling, all in one hands-on project.",
    shortDescription:
      "Price, sell, and count change at a real garage sale.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTlAMzOBftCntpm3NSf6g",
    blobUrl: "",
    imageUrl: "/products/garage-sale-math.jpg",
    previewFile: "Preview Real-world math - Garage sale math.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 104,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-garden-plot-planner",
    name: "Garden Plot Planner",
    slug: "garden-plot-planner",
    description:
      "Design a garden plot using real measurements, area calculations, plant spacing, seed budgets, and seasonal planning. Kids measure, sketch to scale, calculate costs, and plan a planting schedule. Geometry, budgeting, and science growing together in the dirt.",
    shortDescription:
      "Design a garden with real measurements, spacing, and budgets.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTmAMzOBftCntEpC5zsfb",
    blobUrl: "",
    imageUrl: "/products/garden-plot-planner.jpg",
    previewFile: "Preview Real-world math - Garden Plot Planner.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 105,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-party-planner-math",
    name: "Party Planner Math",
    slug: "party-planner-math",
    description:
      "Plan a party from guest list to budget. Calculate food quantities, compare supply costs, figure out timing, and stay within budget. Kids use multiplication, division, estimation, and budgeting to throw a real event. Maths that ends with a party.",
    shortDescription:
      "Plan a party with real budgets, quantities, and timing.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTmAMzOBftCntCKj30Y3C",
    blobUrl: "",
    imageUrl: "/products/party-planner-math.jpg",
    previewFile: "Preview Real-world math - Party Planner Math.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 106,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-road-trip-calculator",
    name: "Road Trip Calculator",
    slug: "road-trip-calculator",
    description:
      "Plan a road trip using real distances, fuel costs, driving times, and travel budgets. Kids calculate mileage, compare routes, estimate fuel expenses, plan stops, and build a complete trip budget. Geography meets maths on the open road.",
    shortDescription:
      "Calculate distances, fuel costs, and budgets for a real road trip.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTnAMzOBftCntxsHa6OHa",
    blobUrl: "",
    imageUrl: "/products/road-trip-calculator.jpg",
    previewFile: "Preview Real-world math - Road trip calculator.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 107,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-savings-goal-tracker",
    name: "Savings Goal Tracker",
    slug: "savings-goal-tracker",
    description:
      "Set a real savings goal and track progress with actual money maths. Kids choose a goal, calculate how long it will take, track deposits, visualise progress, and learn about interest and opportunity cost. Financial literacy that builds real habits.",
    shortDescription:
      "Set and track a real savings goal: deposits, progress, and money maths.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTnAMzOBftCntIbm5J5xU",
    blobUrl: "",
    imageUrl: "/products/savings-goal-tracker.jpg",
    previewFile: "Preview Real-world math - Savings Goal Tracker.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 108,
    active: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "fb-sports-stats-lab",
    name: "Sports Stats Lab",
    slug: "sports-stats-lab",
    description:
      "Collect, analyse, and visualise real sports data. Kids track scores, calculate averages, work out percentages, create charts, and compare player stats. Data literacy and statistics brought to life through the sports they love.",
    shortDescription:
      "Analyse real sports stats: averages, percentages, and data visualisation.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcToAMzOBftCntrNhs4Q1o",
    blobUrl: "",
    imageUrl: "/products/sports-stats-lab.jpg",
    previewFile: "Preview Real-world math - Sports Stats Lab.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 109,
    active: true,
    createdAt: new Date("2025-03-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // LIFE SKILLS
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-skills-map",
    name: "The Future-Ready Skills Map",
    slug: "future-ready-skills-map",
    description:
      "A comprehensive 42-page parent guide to the 10 skills that matter most for your child's future, from emotional intelligence and critical thinking to AI literacy and life skills. Organised into three age bands (0–6, 6–11, 11–14+), each section includes what to develop, what mastery looks like, hands-on activities, a sample week, and a one-page skills-at-a-glance overview.",
    shortDescription:
      "A 42-page parent guide to the 10 skills that matter most, with activities, milestones, and sample weeks for ages 0-14+.",
    priceCents: 999,
    compareAtPriceCents: null,
    stripePriceId: "price_1T9JSZAMzOBftCntfh73EgWC",
    blobUrl: "",
    imageUrl: "/products/future-ready-skills-map.jpg",
    previewFile: "Preview The future-ready skills map.pdf",
    category: "start-here",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 0–14+",
    sortOrder: 90,
    active: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "fb-small-business",
    name: "My Small Business Project",
    slug: "my-small-business-project",
    description:
      "A complete project guide for kids to plan and run their own small business. From brainstorming ideas and researching markets to creating products, setting prices, designing marketing, and tracking profits. Entrepreneurship, financial literacy, and creativity all in one hands-on project.",
    shortDescription:
      "Plan and run a real small business. Entrepreneurship, marketing, and financial literacy.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTpAMzOBftCntQyH6fU3Q",
    blobUrl: "",
    imageUrl: "/products/my-small-business-project.jpg",
    previewFile: "Preview My small business project.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 91,
    active: false,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-time-capsule",
    name: "Time Capsule",
    slug: "time-capsule",
    description:
      "A creative time capsule project that captures who your child is right now. Guided prompts for writing letters to their future self, collecting meaningful items, recording favourites, and reflecting on growth. A beautiful keepsake project that doubles as a writing and self-awareness activity.",
    shortDescription:
      "Capture who your child is right now with guided prompts for a meaningful time capsule.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TFcTpAMzOBftCntpY0VMvLm",
    blobUrl: "",
    imageUrl: "/products/time-capsule.jpg",
    previewFile: "Preview Time Capsule.pdf",
    category: "creativity-anywhere",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 92,
    active: false,
    createdAt: new Date("2025-02-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // COMMUNICATION & WRITING MEGA BUNDLE
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-communication-writing-bundle",
    name: "Communication & Writing Mega Bundle",
    slug: "communication-writing-bundle",
    description:
      "All 10 Communication & Writing guides in one download: adventure storytelling, debate, interviews, recipe writing, magazine creation, trail guides, and more. Every activity puts kids in real communication scenarios where they write, speak, and present for real audiences.",
    shortDescription:
      "All 10 Communication & Writing guides in one download.",
    priceCents: 4499,
    compareAtPriceCents: 5999,
    stripePriceId: "price_1TIVzsAMzOBftCntudyoAMdZ",

    blobUrl: "",
    imageUrl: "/products/mega-bundle-communication-writing.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 6–14",
    sortOrder: 9,
    active: true,
    createdAt: new Date("2025-04-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // ENTREPRENEURSHIP MEGA BUNDLE
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-entrepreneurship-bundle",
    name: "Entrepreneurship Mega Bundle",
    slug: "entrepreneurship-bundle",
    description:
      "All 10 Entrepreneurship guides in one download: brand building, customer discovery, pitching, pricing, marketing, supply chains, and more. Real business skills through hands-on projects, not textbook exercises.",
    shortDescription:
      "All 10 Entrepreneurship guides in one download.",
    priceCents: 4499,
    compareAtPriceCents: 5999,
    stripePriceId: "price_1TIVzsAMzOBftCntL9ZJ2pZ4",

    blobUrl: "",
    imageUrl: "/products/mega-bundle-entrepreneurship.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 6–14",
    sortOrder: 10,
    active: true,
    createdAt: new Date("2025-04-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // PLANNING & PROBLEM-SOLVING MEGA BUNDLE
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-planning-problem-solving-bundle",
    name: "Planning & Problem-Solving Mega Bundle",
    slug: "planning-problem-solving-bundle",
    description:
      "All 10 Planning & Problem-Solving guides in one download: survival planning, emergency prep, decision-making, scavenger hunts, everyday redesign, and more. Kids practise thinking ahead, solving real problems, and making smart decisions.",
    shortDescription:
      "All 10 Planning & Problem-Solving guides in one download.",
    priceCents: 4499,
    compareAtPriceCents: 5999,
    stripePriceId: "price_1TIVzqAMzOBftCntHOBpwe5o",

    blobUrl: "",
    imageUrl: "/products/mega-bundle-planning-problem-solving.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 6–14",
    sortOrder: 11,
    active: true,
    createdAt: new Date("2025-04-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // COMMUNICATION & WRITING - Individual Guides
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-adventure-story-map",
    name: "Adventure Story Map",
    slug: "adventure-story-map",
    description:
      "A visual story-mapping project that guides kids through planning and writing their own adventure narrative. They map out characters, settings, plot twists, and story arcs, then write the story. Creative writing through spatial thinking and real storytelling craft.",
    shortDescription:
      "Plan and write an adventure story using visual story mapping.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GAAMzOBftCntUbwhJrGi",
    blobUrl: "",
    imageUrl: "/products/adventure-story-map.jpg",
    previewFile: "Preview Communication & Writing - Adventure Story Map.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 110,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-community-tour-guide",
    name: "Community Tour Guide",
    slug: "community-tour-guide",
    description:
      "Research, write, and present a guided tour of your community. Kids choose what matters most about where they live, practise descriptive language, and build presentation skills. Real-world communication through local storytelling.",
    shortDescription:
      "Create a guided tour of your community.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GBAMzOBftCntAm9Aoepf",
    blobUrl: "",
    imageUrl: "/products/community-tour-guide.jpg",
    previewFile: "Preview Communication & Writing - Community Tour Guide.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 111,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-directions-challenge",
    name: "Directions Challenge",
    slug: "directions-challenge",
    description:
      "Write clear, step-by-step directions and test whether someone else can follow them. Kids discover how hard it is to communicate clearly, and get better at it through practice and feedback. Precision writing that builds real communication skills.",
    shortDescription:
      "Write and test clear step-by-step directions.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GBAMzOBftCntTpdwvrbU",
    blobUrl: "",
    imageUrl: "/products/directions-challenge.jpg",
    previewFile: "Preview Communication & Writing - Directions Challenge.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 112,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-family-debate-night",
    name: "Family Debate Night",
    slug: "family-debate-night",
    description:
      "A structured family debate framework that teaches persuasive speaking, active listening, and respectful disagreement. Kids prepare arguments, present their case, and learn to respond thoughtfully. Communication skills the whole family practises together.",
    shortDescription:
      "Family debate and persuasion skills.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GCAMzOBftCnto2VZdQ3c",
    blobUrl: "",
    imageUrl: "/products/family-debate-night.jpg",
    previewFile: "Preview Communication & Writing - Family Debate Night.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 113,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-family-recipe-book",
    name: "Family Recipe Book",
    slug: "family-recipe-book",
    description:
      "Document family recipes with clear procedural writing and personal stories. Kids interview family members, write step-by-step instructions, and create a keepsake recipe book. Combines procedural writing, narrative storytelling, and family connection.",
    shortDescription:
      "Create a family recipe book with stories and instructions.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GCAMzOBftCntuLVAWPzs",
    blobUrl: "",
    imageUrl: "/products/family-recipe-book.jpg",
    previewFile: "Preview Communication & Writing - Family Recipe Book.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 114,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-market-stall-pitch",
    name: "Market Stall Pitch",
    slug: "market-stall-pitch",
    description:
      "Create a persuasive pitch to sell a product or service at a market stall. Kids practise the art of persuasion: choosing words that connect, reading their audience, and presenting with confidence. Communication meets entrepreneurship in one hands-on activity.",
    shortDescription:
      "Practise persuasive selling and pitching.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GDAMzOBftCntghOF1GUa",
    blobUrl: "",
    imageUrl: "/products/market-stall-pitch.jpg",
    previewFile: "Preview Communication & Writing - Market Stall Pitch.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 115,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-mini-magazine-creator",
    name: "Mini Magazine Creator",
    slug: "mini-magazine-creator",
    description:
      "Write and design a mini magazine from scratch: headlines, articles, illustrations, and advertisements. Kids work with multiple text types in one project, learning layout, design, and how different writing styles serve different purposes. A publishing project that builds real writing range.",
    shortDescription:
      "Write and design a mini magazine.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GEAMzOBftCnt9udrGsJD",
    blobUrl: "",
    imageUrl: "/products/mini-magazine-creator.jpg",
    previewFile: "Preview Communication & Writing - Mini Magazine Creator.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 116,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-my-review-column",
    name: "My Review Column",
    slug: "my-review-column",
    description:
      "Write reviews of books, movies, products, or experiences. Kids develop critical analysis skills and learn to express opinions clearly with supporting evidence. Opinion writing that builds confidence and teaches kids their perspective matters.",
    shortDescription:
      "Write reviews and develop opinion writing skills.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GFAMzOBftCntPFZFuBEl",
    blobUrl: "",
    imageUrl: "/products/my-review-column.jpg",
    previewFile: "Preview Communication & Writing - My Review Column.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 117,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-neighbourhood-interview",
    name: "Neighbourhood Interview Project",
    slug: "neighbourhood-interview",
    description:
      "Interview people in your community: neighbours, shop owners, local heroes. Kids prepare questions, practise active listening, and present the stories they gather. Builds interviewing skills, empathy, and the ability to communicate someone else's story with care.",
    shortDescription:
      "Interview community members and share their stories.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GFAMzOBftCntGvNlORlP",
    blobUrl: "",
    imageUrl: "/products/neighbourhood-interview.jpg",
    previewFile: "Preview Communication & Writing - Neighbourhood Interview Project.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 118,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-trail-guide-creator",
    name: "Trail Guide Creator",
    slug: "trail-guide-creator",
    description:
      "Create a written guide to a local trail or walking path using descriptive language and observation skills. Kids walk the trail, take notes, and write a guide that others could follow. Outdoor observation meets descriptive writing in one meaningful project.",
    shortDescription:
      "Write a guide to a local trail or walking path.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GGAMzOBftCntTdGeIrzv",
    blobUrl: "",
    imageUrl: "/products/trail-guide-creator.jpg",
    previewFile: "Preview Communication & Writing - Trail Guide Creator.pdf",
    category: "communication-writing",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 119,
    active: true,
    createdAt: new Date("2025-04-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // ENTREPRENEURSHIP - Individual Guides
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-brand-builder",
    name: "Brand Builder",
    slug: "brand-builder",
    description:
      "Build a brand identity from scratch: name, logo, personality, values, and visual style. Kids learn what makes a brand memorable and create their own from the ground up. Creativity meets communication in a project that teaches marketing thinking.",
    shortDescription:
      "Build a complete brand identity from scratch.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GGAMzOBftCntHmHXpl3q",
    blobUrl: "",
    imageUrl: "/products/brand-builder.jpg",
    previewFile: "Preview Entrepreneurship - Brand builder.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 120,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-business-failure-lab",
    name: "Business Failure Lab",
    slug: "business-failure-lab",
    description:
      "Analyse real business failures, figure out what went wrong, and learn from other people's mistakes. Kids build resilience, critical thinking, and the understanding that failure is part of the process. Entrepreneurship education that starts with what not to do.",
    shortDescription:
      "Learn from real business failures.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GHAMzOBftCntkFhyJgc4",
    blobUrl: "",
    imageUrl: "/products/business-failure-lab.jpg",
    previewFile: "Preview Entrepreneurship - Business Failure Lab.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 121,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-community-service-business",
    name: "Community Service Business",
    slug: "community-service-business",
    description:
      "Design and launch a service-based business with a social mission. Kids combine entrepreneurship with empathy, finding a community need and building a business that helps. Social entrepreneurship that teaches planning, service, and impact.",
    shortDescription:
      "Build a business that helps your community.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GIAMzOBftCntGC68Cjjv",
    blobUrl: "",
    imageUrl: "/products/community-service-business.jpg",
    previewFile: "Preview Entrepreneurship - Community Service Business.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 122,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-customer-discovery",
    name: "Customer Discovery Challenge",
    slug: "customer-discovery",
    description:
      "Conduct real customer interviews, gather feedback, and use it to refine a business idea. Kids learn to listen before they build, the most important entrepreneurship skill there is. Research, communication, and critical thinking in one hands-on challenge.",
    shortDescription:
      "Interview real customers and refine a business idea.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GIAMzOBftCnt8GwxU2iZ",
    blobUrl: "",
    imageUrl: "/products/customer-discovery.jpg",
    previewFile: "Preview Entrepreneurship - Customer Discovery Challenge.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 123,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-investor-pitch",
    name: "Investor Pitch Portfolio",
    slug: "investor-pitch",
    description:
      "Create a compelling investor pitch with financial reasoning, risk assessment, and persuasive presentation. Kids learn to communicate the value of an idea, back it up with numbers, and present with confidence. Business thinking meets public speaking.",
    shortDescription:
      "Build and deliver an investor pitch.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GJAMzOBftCntxUJOLzau",
    blobUrl: "",
    imageUrl: "/products/investor-pitch.jpg",
    previewFile: "Preview Entrepreneurship - Investor Pitch Portfolio.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 124,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-marketing-campaign",
    name: "Marketing Campaign Creator",
    slug: "marketing-campaign",
    description:
      "Design and execute a marketing campaign to reach a real audience. Kids learn about target audiences, messaging, creative assets, and campaign planning. Persuasion, creativity, and communication skills applied to a real marketing project.",
    shortDescription:
      "Create a marketing campaign from scratch.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GKAMzOBftCnt9BS5xNz5",
    blobUrl: "",
    imageUrl: "/products/marketing-campaign.jpg",
    previewFile: "Preview Entrepreneurship - Marketing Campaign Creator.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 125,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-pricing-experiment",
    name: "Pricing Experiment",
    slug: "pricing-experiment",
    description:
      "Test different pricing strategies and discover what makes people willing to pay. Kids experiment with value, perception, and financial decision-making. Critical thinking and financial literacy through hands-on experimentation.",
    shortDescription:
      "Experiment with pricing strategies.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GKAMzOBftCnttAaAv04s",
    blobUrl: "",
    imageUrl: "/products/pricing-experiment.jpg",
    previewFile: "Preview Entrepreneurship - Pricing Experiment.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 126,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-product-design-lab",
    name: "Product Design Lab",
    slug: "product-design-lab",
    description:
      "Use design thinking to create a product that solves a real problem. Kids identify needs, brainstorm solutions, build prototypes, test with users, and iterate. The same process real designers and engineers use, scaled for kids.",
    shortDescription:
      "Design a product that solves a real problem.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GLAMzOBftCntEEPt0NQu",
    blobUrl: "",
    imageUrl: "/products/product-design-lab.jpg",
    previewFile: "Preview Entrepreneurship - Product Design Lab.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 127,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-supply-chain-detective",
    name: "Supply Chain Detective",
    slug: "supply-chain-detective",
    description:
      "Trace a product's journey from raw materials to your front door. Kids investigate supply chains, understand global systems, and think critically about where things come from. Systems thinking, geography, and critical analysis in one investigation project.",
    shortDescription:
      "Investigate real supply chains from source to consumer.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GLAMzOBftCnth5ZiVQQd",
    blobUrl: "",
    imageUrl: "/products/supply-chain-detective.jpg",
    previewFile: "Preview Entrepreneurship - Supply Chain Detective.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 128,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-shark-tank-pitch",
    name: "The Shark Tank Pitch",
    slug: "shark-tank-pitch",
    description:
      "Develop and deliver a high-stakes business pitch, Shark Tank style. Kids create a business concept, build financial projections, design a presentation, and pitch to their family. Public speaking, financial thinking, and entrepreneurship all in one thrilling project.",
    shortDescription:
      "Pitch a business idea Shark Tank style.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GMAMzOBftCntLlF5M3KM",
    blobUrl: "",
    imageUrl: "/products/shark-tank-pitch.jpg",
    previewFile: "Preview Entrepreneurship - The Shark Tank Pitch.pdf",
    category: "entrepreneurship",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 129,
    active: true,
    createdAt: new Date("2025-04-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // PLANNING & PROBLEM-SOLVING - Individual Guides
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-emergency-ready",
    name: "Emergency Ready Challenge",
    slug: "emergency-ready",
    description:
      "Help kids think clearly under pressure and build confidence handling the unexpected. Activities cover emergency preparedness, decision-making under stress, and practical planning for real-world scenarios. Life skills that build genuine confidence.",
    shortDescription:
      "Emergency preparedness and clear thinking under pressure.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GNAMzOBftCnt6j6LmAoW",
    blobUrl: "",
    imageUrl: "/products/emergency-ready.jpg",
    previewFile: "Preview Planning & Problem-Solving Emergency Ready Challenge.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 130,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-everyday-redesign",
    name: "Everyday Redesign Challenge",
    slug: "everyday-redesign",
    description:
      "Look at everyday objects and systems with fresh eyes, then redesign them to work better. Kids practise systems thinking, observation, and creative problem-solving by improving the things they use every day. Design thinking applied to real life.",
    shortDescription:
      "Redesign everyday objects and systems.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GNAMzOBftCntHGQS5eUS",
    blobUrl: "",
    imageUrl: "/products/everyday-redesign.jpg",
    previewFile: "Preview Planning & Problem-Solving Everyday Redesign Challenge.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 131,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-fix-it-detective",
    name: "Fix-It Detective",
    slug: "fix-it-detective",
    description:
      "Diagnose and fix real household problems using logic, observation, and resourcefulness. Kids learn to troubleshoot, from a leaky tap to a stuck drawer, building practical skills and the confidence to figure things out. Problem-solving that's genuinely useful.",
    shortDescription:
      "Fix real household problems with logic and resourcefulness.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GOAMzOBftCnt6Tpat3LR",
    blobUrl: "",
    imageUrl: "/products/fix-it-detective.jpg",
    previewFile: "Preview Planning & Problem-Solving Fix-it detective.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 132,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-neighbourhood-problem-spotter",
    name: "Neighbourhood Problem Spotter",
    slug: "neighbourhood-problem-spotter",
    description:
      "Walk your neighbourhood with fresh eyes. Spot real problems, think about causes, and brainstorm solutions. Kids practise observation, critical thinking, and civic engagement. The kind of problem-solving that connects kids to their community.",
    shortDescription:
      "Spot and solve real neighbourhood problems.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GPAMzOBftCntVfIvMsTm",
    blobUrl: "",
    imageUrl: "/products/neighbourhood-problem-spotter.jpg",
    previewFile: "Preview Planning & Problem-Solving Neighbourhood Problem Spotter.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 133,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-outdoor-survival-planner",
    name: "Outdoor Survival Planner",
    slug: "outdoor-survival-planner",
    description:
      "Plan outdoor expeditions, think through survival scenarios, and build real outdoor planning skills. Kids research terrain, assess risks, plan supplies, and make decisions about shelter, water, and navigation. Adventure planning that builds critical thinking.",
    shortDescription:
      "Plan outdoor survival adventures and expeditions.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GPAMzOBftCntFrydEXl8",
    blobUrl: "",
    imageUrl: "/products/outdoor-survival-planner.jpg",
    previewFile: "Preview Planning & Problem-Solving Outdoor survival planner.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 134,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-pack-like-a-pro",
    name: "Pack Like a Pro",
    slug: "pack-like-a-pro",
    description:
      "Master the art of strategic packing: priorities, weight, space management, and logistics. Kids learn to think ahead, make trade-offs, and plan for different scenarios. A surprisingly deep planning challenge that builds executive function skills.",
    shortDescription:
      "Master strategic packing and planning.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GQAMzOBftCntb8riv2Sa",
    blobUrl: "",
    imageUrl: "/products/pack-like-a-pro.jpg",
    previewFile: "Preview Planning & Problem-Solving Pack Like a Pro.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 135,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-scavenger-hunt-designer",
    name: "Scavenger Hunt Designer",
    slug: "scavenger-hunt-designer",
    description:
      "Design, create, and test your own scavenger hunts for friends and family. Kids plan clues, set challenge levels, think about pacing, and iterate based on feedback. A creative planning project that builds logic, writing, and design thinking.",
    shortDescription:
      "Design your own scavenger hunts.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GRAMzOBftCntSX6HUHfn",
    blobUrl: "",
    imageUrl: "/products/scavenger-hunt-designer.jpg",
    previewFile: "Preview Planning & Problem-Solving Scavenger Hunt Designer.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 136,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-swap-day-challenge",
    name: "The Swap Day Challenge",
    slug: "swap-day-challenge",
    description:
      "Plan and execute a swap day where kids take on someone else's role or responsibilities. Builds empathy, planning skills, and appreciation for what others do. A unique challenge that changes how kids see the people around them.",
    shortDescription:
      "Swap roles for a day. Empathy through experience.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GRAMzOBftCntDaWFbi9o",
    blobUrl: "",
    imageUrl: "/products/swap-day-challenge.jpg",
    previewFile: "Preview Planning & Problem-Solving The Swap Day Challenge.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 137,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-what-if-scenario-lab",
    name: "The What-If Scenario Lab",
    slug: "what-if-scenario-lab",
    description:
      "Explore hypothetical scenarios, predict outcomes, and plan responses. Kids work through 'what if' situations that stretch their thinking, from everyday dilemmas to wild scenarios. Speculative thinking that builds planning skills and creative problem-solving.",
    shortDescription:
      "Explore what-if scenarios and plan responses.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GSAMzOBftCntJ3g4f5lm",
    blobUrl: "",
    imageUrl: "/products/what-if-scenario-lab.jpg",
    previewFile: "Preview Planning & Problem-Solving The What If Scenario Lab.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 138,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "fb-decision-lab",
    name: "What Would You Do? Decision Lab",
    slug: "decision-lab",
    description:
      "Work through real decision scenarios, weigh options, consider consequences, and justify choices. Kids practise the kind of thoughtful decision-making that builds confidence and independence. Critical thinking applied to everyday life.",
    shortDescription:
      "Practise real-world decision-making.",
    priceCents: 599,
    compareAtPriceCents: null,
    stripePriceId: "price_1TJ6GSAMzOBftCnttbvtwfLP",
    blobUrl: "",
    imageUrl: "/products/decision-lab.jpg",
    previewFile: "Preview Planning & Problem-Solving What Would You Do Decision Lab.pdf",
    category: "planning-problem-solving",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 139,
    active: true,
    createdAt: new Date("2025-04-01"),
  },
];

export function getFallbackProductBySlug(slug: string): FallbackProduct | null {
  return fallbackProducts.find((p) => p.slug === slug) ?? null;
}

export function getFallbackProducts(): FallbackProduct[] {
  return fallbackProducts.filter((p) => p.active);
}

export function searchFallbackProducts(query: string): FallbackProduct[] {
  const q = query.toLowerCase();
  return fallbackProducts.filter(
    (p) =>
      p.active &&
      (p.name.toLowerCase().includes(q) ||
        p.shortDescription.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q)),
  );
}

export function filterByAge<T extends { ageRange?: string | null }>(
  products: T[],
  minAge: number,
): T[] {
  return products.filter((p) => {
    if (!p.ageRange) return true;
    // Extract first number from ageRange like "Ages 6–14" → 4
    const match = p.ageRange.match(/(\d+)/);
    if (!match) return true;
    const productMinAge = parseInt(match[1], 10);
    return productMinAge <= minAge;
  });
}

export function getProductCounts(products: { category: string }[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const p of products) {
    counts[p.category] = (counts[p.category] || 0) + 1;
  }
  return counts;
}
