/**
 * Hardcoded product data used when the database is unavailable.
 * Both the shop listing and product detail pages fall back to this data.
 */

export interface FallbackProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  priceCents: number;
  compareAtPriceCents: number | null;
  stripePriceId: string;
  blobUrl: string;
  imageUrl: string | null;
  previewFile: string | null;
  category: string;
  isBundle: boolean;
  bundleProductIds: string | null;
  activityCount: number | null;
  ageRange: string | null;
  sortOrder: number;
  active: boolean;
  createdAt: Date;
}

// ─── Helper: all individual product prices summed for Master Bundle compareAt ───
// Existing: Nature Journal $9.99, Spring $14.99, Kitchen Maths $9.99, Creative Thinking $9.99, Skills Map $9.99
// New (41 products × $4.99): $204.59
// Total: 9.99 + 14.99 + 9.99 + 9.99 + 9.99 + (41 × 4.99) = 259.54 → 25954 cents

export const fallbackProducts: FallbackProduct[] = [
  // ─────────────────────────────────────────────────────────────
  // BUNDLES
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-master-bundle",
    name: "Master Bundle (Everything)",
    slug: "master-bundle",
    description:
      "Every activity pack we make, in one instant download. Nature, creativity, real-world skills, AI literacy, seasonal adventures, and life skills — all of it. New packs are added as we create them, and you'll get those too. This is everything your family needs for years of meaningful, no-prep learning.",
    shortDescription:
      "Every activity pack we make — all categories, all ages, one download.",
    priceCents: 8999,
    compareAtPriceCents: 25954,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/mega-bundle-preview.jpg",
    previewFile: "Mega bundle preview.pdf",
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 220,
    ageRange: "Ages 4–14",
    sortOrder: 0,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-seasonal-bundle",
    name: "Full Seasonal Bundle",
    slug: "seasonal-bundle",
    description:
      "All four seasonal packs in one download — spring, summer, autumn, and winter. 80 outdoor activities designed to match each season's unique energy and opportunities. From spring planting and bird-watching to winter star-gazing and ice experiments. Your family gets a full year of outdoor learning, ready to use whenever the season changes.",
    shortDescription:
      "All 4 seasonal packs — 80 outdoor activities for every time of year.",
    priceCents: 4999,
    compareAtPriceCents: 2995,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/four-seasons-bundle.jpg",
    previewFile: "Preview 4 seasons bundle.pdf",
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 80,
    ageRange: "Ages 4–14",
    sortOrder: 1,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-creativity-mega-bundle",
    name: "Creativity & Imagination Mega Bundle",
    slug: "creativity-mega-bundle",
    description:
      "All 10 Creativity Anywhere projects in one download. From building board games and Rube Goldberg machines to creating theme parks, museums, and stop-motion films — each project is a multi-step creative adventure that builds design thinking, problem-solving, and artistic confidence. 10 complete projects, zero prep required.",
    shortDescription:
      "All 10 Creativity Anywhere projects — design, build, and create without limits.",
    priceCents: 2999,
    compareAtPriceCents: 4990,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/mega-bundle-creativity.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 6–14",
    sortOrder: 2,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-real-world-mega-bundle",
    name: "Real-World Relevance Mega Bundle",
    slug: "real-world-mega-bundle",
    description:
      "All 10 Real-World Relevance challenges in one download. Budgeting, meal planning, micro-businesses, media literacy, travel planning, smart shopping, and more. Each challenge puts kids in real-life scenarios where they practise the skills that actually matter — critical thinking, financial literacy, communication, and problem-solving.",
    shortDescription:
      "All 10 Real-World Relevance challenges — life skills, financial literacy, and project-based learning.",
    priceCents: 2999,
    compareAtPriceCents: 4990,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/mega-bundle-real-world.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 9–14",
    sortOrder: 3,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-ai-digital-bundle",
    name: "AI & Digital Literacy Bundle",
    slug: "ai-digital-bundle",
    description:
      "All 10 AI & Digital Literacy activities in one download. From understanding what AI actually is, to spotting deepfakes, checking for bias, building ethical AI projects, and managing digital boundaries. Each activity is designed for ages 9–14 and helps kids become critical, confident, and responsible digital citizens.",
    shortDescription:
      "All 10 AI & Digital Literacy activities — responsible tech, critical thinking, and digital citizenship.",
    priceCents: 2999,
    compareAtPriceCents: 4990,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/mega-bundle-ai-digital.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: 10,
    ageRange: "Ages 9–14",
    sortOrder: 4,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-nature-art-bundle",
    name: "Nature Art Bundle",
    slug: "nature-art-bundle",
    description:
      "Three of our most popular nature packs together — Land Art Challenge Cards, Nature Crafts for Kids, and the Nature Journal. From building sculptures with sticks and stones to pressing flowers, sketching wildlife, and creating nature mandalas. Everything your family needs to turn the outdoors into an art studio.",
    shortDescription:
      "Land Art + Nature Crafts + Nature Journal — turn the outdoors into an art studio.",
    priceCents: 2999,
    compareAtPriceCents: 1497,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/nature-art-bundle.jpg",
    previewFile: null,
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 4–14",
    sortOrder: 5,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-outdoor-toolkit-bundle",
    name: "Outdoor Learning Toolkit Bundle",
    slug: "outdoor-toolkit-bundle",
    description:
      "Four essential outdoor learning packs in one download — Nature Walk Task Cards, Outdoor Learning Missions, STEM Challenge Cards, and Nature Choice Boards. Whether you're in the backyard, at the park, or on a trail, these cards give your kids a reason to explore, observe, test, and discover. Zero prep, maximum outdoor time.",
    shortDescription:
      "Nature Walk Cards + Missions + STEM Challenges + Choice Boards — your complete outdoor toolkit.",
    priceCents: 2999,
    compareAtPriceCents: 1996,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/outdoor-toolkit-bundle.jpg",
    previewFile: "Preview Toolkit bundle.pdf",
    category: "bundle",
    isBundle: true,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 4–14",
    sortOrder: 6,
    active: true,
    createdAt: new Date("2025-01-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // NATURE — Seasonal packs (merged into Nature)
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-spring-outdoor",
    name: "Spring Outdoor Learning Pack",
    slug: "spring-outdoor-pack",
    description:
      "20 outdoor activities that use spring's energy to build real-world skills. Plant a seed and track its growth. Build a bug hotel. Create a rain gauge from a jar. Map the birds in your garden. Every activity connects to science, maths, or literacy — but feels like adventure, not homework.",
    shortDescription:
      "20 outdoor activities that use spring's energy to build real-world skills.",
    priceCents: 1499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/spring-outdoor-pack.jpg",
    previewFile: "Preview Anywhere Learning Spring.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 4–14",
    sortOrder: 10,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-summer-outdoor",
    name: "Summer Outdoor Learning Pack",
    slug: "summer-outdoor-pack",
    description:
      "20 summer activities for families who learn on the move. Water experiments, shadow tracking, outdoor cooking, beach science, and more. Designed for long sunny days when kids have energy to burn and curiosity to spare.",
    shortDescription:
      "20 summer activities — water experiments, outdoor cooking, and sun-powered learning.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/summer-outdoor-pack.jpg",
    previewFile: "Preview Anywhere Learning Summer.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 4–14",
    sortOrder: 11,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-fall-outdoor",
    name: "Fall Outdoor Learning Pack",
    slug: "fall-outdoor-pack",
    description:
      "20 autumn activities that use the changing season to build observation and creative skills. Leaf collecting, weather tracking, nature journaling, harvest maths, and more. Perfect for families who want to make the most of shorter days and golden light.",
    shortDescription:
      "20 autumn activities — leaf science, harvest maths, and seasonal observation.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/fall-outdoor-pack.jpg",
    previewFile: "Preview Anywhere Learning Fall.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 4–14",
    sortOrder: 12,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-winter-outdoor",
    name: "Winter Outdoor Learning Pack",
    slug: "winter-outdoor-pack",
    description:
      "20 winter activities for cosy indoor days and cold outdoor adventures. Ice experiments, star-gazing, shadow play, winter bird feeding, and fireside storytelling. Designed for families who want to keep learning alive even when the weather says stay inside.",
    shortDescription:
      "20 winter activities — ice experiments, star-gazing, and cosy indoor learning.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/winter-outdoor-pack.jpg",
    previewFile: "Preview Anywhere Learning Winter.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 4–14",
    sortOrder: 13,
    active: true,
    createdAt: new Date("2025-01-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // NATURE
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-nature-journal",
    name: "Nature Journal & Walk Cards",
    slug: "nature-journal-walks",
    description:
      "25 nature walk prompts and journaling activities that turn any outdoor walk into a rich observation and science experience. Each card gives your child a specific focus — tracking shadows, sketching bark patterns, listening for bird calls, mapping a puddle ecosystem. No nature expertise required from you. Just open a card, step outside, and let curiosity lead.",
    shortDescription:
      "25 nature walk prompts and journaling activities for rich outdoor observation.",
    priceCents: 999,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/nature-journal-walks.jpg",
    previewFile: "Preview My nature journal.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 25,
    ageRange: "Ages 4–14",
    sortOrder: 20,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-nature-walk-tasks",
    name: "Nature Walk Task Cards",
    slug: "nature-walk-task-cards",
    description:
      "Task cards that turn any walk into a focused nature exploration. Each card gives kids a specific mission — find three textures, listen for five sounds, sketch the smallest thing you can find. Works in any outdoor space, any season, any weather.",
    shortDescription:
      "Task cards that turn any walk into a focused nature exploration.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/nature-walk-task-cards.jpg",
    previewFile: "Preview Nature Walk Task Cards.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 4–14",
    sortOrder: 21,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-nature-choice-boards",
    name: "Nature Choice Boards",
    slug: "nature-choice-boards",
    description:
      "Choose-your-own-adventure style nature activities. Each board gives kids 9 options to pick from — observe, create, explore, or investigate. Perfect for self-directed learners who want to choose what to do outside. Works in backyards, parks, forests, and beaches.",
    shortDescription:
      "Choose-your-own-adventure nature activities — 9 options per board, self-directed outdoor learning.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/nature-choice-boards.jpg",
    previewFile: "Preview Nature Choice Boards.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 4–14",
    sortOrder: 22,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-outdoor-missions",
    name: "Outdoor Learning Missions",
    slug: "outdoor-learning-missions",
    description:
      "Mission-style outdoor challenges that get kids moving, observing, and problem-solving in nature. Each mission has a clear objective, steps to follow, and a reflection prompt. From building shelters to mapping wildlife trails — real adventures that feel important.",
    shortDescription:
      "Mission-style outdoor challenges — build, explore, observe, and problem-solve in nature.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/outdoor-learning-missions.jpg",
    previewFile: "Preview Outdoor learning missions.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 4–14",
    sortOrder: 23,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-outdoor-stem",
    name: "Outdoor STEM Challenge Cards",
    slug: "outdoor-stem-challenges",
    description:
      "20 outdoor STEM challenges that use the natural world as a laboratory. Build a bridge from sticks. Design a waterproof shelter. Measure tree heights using shadows. Engineer a boat that floats. Each challenge has constraints that force creative problem-solving — no instructions, just goals.",
    shortDescription:
      "20 outdoor STEM challenges — build, test, and engineer using what nature provides.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/outdoor-stem-challenges.jpg",
    previewFile: "Preview Outdoor STEM Challenge Cards.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 20,
    ageRange: "Ages 4–14",
    sortOrder: 24,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-land-art",
    name: "Land Art Challenge Cards",
    slug: "land-art-challenges",
    description:
      "15 land art challenges that turn natural materials into beautiful, temporary art. Create a mandala from stones. Build a spiral from leaves. Arrange colours from the forest floor. Kids learn about patterns, symmetry, and design — all while being creative outdoors with zero mess to clean up.",
    shortDescription:
      "15 land art challenges — create beautiful, temporary art using natural materials.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/land-art-challenges.jpg",
    previewFile: "Preview Land Art Challenge Cards.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: 15,
    ageRange: "Ages 4–14",
    sortOrder: 25,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-nature-crafts",
    name: "Nature Crafts for Kids",
    slug: "nature-crafts",
    description:
      "Hands-on nature craft projects using materials found outdoors. Leaf pressing, stick weaving, flower pounding, bark rubbings, and more. Each project connects creativity with nature observation — kids collect materials, then create something beautiful with what they find.",
    shortDescription:
      "Hands-on nature craft projects using materials found outdoors.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/nature-crafts.jpg",
    previewFile: "Preview Nature crafts for kids.pdf",
    category: "nature",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 4–14",
    sortOrder: 26,
    active: true,
    createdAt: new Date("2025-01-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // CREATIVITY
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-board-game-studio",
    name: "Board Game Studio",
    slug: "board-game-studio",
    description:
      "Design, build, and playtest an original board game from scratch. Kids brainstorm themes, create rules, design the board, craft game pieces, and iterate based on playtesting. A complete creative project that builds design thinking, strategic reasoning, and communication skills.",
    shortDescription:
      "Design, build, and playtest an original board game from scratch.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/board-game-studio.jpg",
    previewFile: "Preview Creativity anywhere Board game studio.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 31,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-rube-goldberg",
    name: "Build a Rube Goldberg Machine",
    slug: "rube-goldberg-machine",
    description:
      "Build an absurdly complicated machine to do something simple. Kids design chain reactions using everyday materials — dominoes, ramps, balls, levers. Each step teaches engineering principles, cause-and-effect thinking, and creative problem-solving. Failure is part of the fun.",
    shortDescription:
      "Build an absurdly complicated machine to do something simple — engineering meets creativity.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/rube-goldberg-machine.jpg",
    previewFile: "Preview Creativity anywhere Build a Rube Goldberg Machine.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 32,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-survival-base",
    name: "Build a Survival Base",
    slug: "survival-base",
    description:
      "Design and build a survival base for an imaginary expedition. Kids choose a biome, research challenges, plan their base layout, create models, and present their design. Combines geography, engineering, creative writing, and problem-solving in one immersive project.",
    shortDescription:
      "Design a survival base for an imaginary expedition — geography meets engineering.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/survival-base.jpg",
    previewFile: "Preview Creativity anywhere Build a Survival Base for an Imaginary Expedition.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 33,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-imaginary-world",
    name: "Build an Imaginary World",
    slug: "imaginary-world",
    description:
      "Create an entire imaginary world from scratch — its geography, creatures, rules, languages, and stories. Kids build maps, design ecosystems, invent civilisations, and write lore. A massive open-ended creative project that can last days or weeks.",
    shortDescription:
      "Create an entire imaginary world — geography, creatures, rules, and stories.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/imaginary-world.jpg",
    previewFile: "Preview Creativity anywhere Build an imaginary world.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 34,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-creature-habitat",
    name: "Create a Creature + Build Its Habitat",
    slug: "creature-habitat",
    description:
      "Invent a brand-new creature and build its entire habitat. Kids design anatomy, diet, behaviour, and environment. Then they construct a physical model of the habitat. Combines biology, art, engineering, and creative writing in one unforgettable project.",
    shortDescription:
      "Invent a creature and build its habitat — biology meets art and engineering.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/creature-habitat.jpg",
    previewFile: "Preview Creativity anywhere Create a Creature + Build Its Habitat.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 35,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-theme-park",
    name: "Create a Theme Park or Adventure Course",
    slug: "theme-park",
    description:
      "Design a theme park or adventure course from concept to completion. Kids plan rides, map layouts, calculate budgets, design marketing materials, and build scale models. A project that combines maths, art, engineering, and business thinking.",
    shortDescription:
      "Design a theme park — plan rides, map layouts, and build scale models.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/theme-park.jpg",
    previewFile: "Preview Creativity anywhere Create a Theme Park or Adventure Course.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 36,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-mini-movie",
    name: "Create a Mini Movie or Radio Drama",
    slug: "mini-movie",
    description:
      "Create a mini movie, stop-motion animation, or radio drama from scratch. Kids write scripts, design sets, create characters, record audio, and edit their production. A full creative process from concept to premiere — no fancy equipment needed, just a phone and imagination.",
    shortDescription:
      "Create a mini movie, stop-motion, or radio drama — script to premiere.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/mini-movie.jpg",
    previewFile: "Preview Creativity anywhere Create a mini movie,  stop-motion or radio drama.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 37,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-invent-sport",
    name: "Invent a New Sport",
    slug: "invent-a-sport",
    description:
      "Create an entirely new sport with original rules, equipment, and scoring. Kids design the game, build equipment from everyday materials, write a rulebook, playtest with family, and iterate. A masterclass in creative thinking, negotiation, and physical activity.",
    shortDescription:
      "Create an entirely new sport — design rules, build equipment, and playtest.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/invent-a-sport.jpg",
    previewFile: "Preview Creativity anywhere Invent a new sport.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 38,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-kinetic-sculpture",
    name: "Kinetic Sculpture or Art Installation",
    slug: "kinetic-sculpture",
    description:
      "Design and build a kinetic sculpture or interactive art installation. Kids explore movement, balance, wind, and gravity to create art that moves. Combines physics, engineering, and artistic expression in a hands-on project that produces something genuinely impressive.",
    shortDescription:
      "Build a kinetic sculpture — art that moves using physics and engineering.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/kinetic-sculpture.jpg",
    previewFile: "Preview Creativity anywhere Kinetic Sculpture or Art Installation.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 39,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-build-museum",
    name: "Build a Museum or Interactive Exhibit",
    slug: "build-a-museum",
    description:
      "Create a museum or interactive exhibit on any topic your child loves. Research, curate, design displays, write labels, build interactive elements, and host a grand opening. A project that teaches research, writing, presentation, and design — all driven by your child's own interests.",
    shortDescription:
      "Create a museum exhibit — research, curate, design, and host a grand opening.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/build-a-museum.jpg",
    previewFile: "Preview Creativity anywhere build a museum or interactive exhibit.pdf",
    category: "creativity",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 40,
    active: true,
    createdAt: new Date("2025-01-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // REAL-WORLD MATH, CRITICAL THINKING, SELF-MANAGEMENT & LITERACY
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-budget-challenge",
    name: "Real-Life Budget Challenge",
    slug: "budget-challenge",
    description:
      "Real-money challenges that teach kids budgeting and smart spending. Kids plan a meal on a budget, track family spending for a week, compare prices at different shops, and design their own savings plan. Financial literacy through real-world practice, not worksheets.",
    shortDescription:
      "Real-money challenges that teach kids budgeting, saving, and smart spending.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/budget-challenge.jpg",
    previewFile: "Preview Real-world relevance Budget challenge.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 51,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-community-impact",
    name: "Community Impact Project",
    slug: "community-impact",
    description:
      "Guide your child through planning and executing a real community impact project. From identifying local needs to designing solutions, creating action plans, and reflecting on results. Builds empathy, planning skills, and a sense of civic responsibility.",
    shortDescription:
      "Plan and execute a real community impact project — empathy in action.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/community-impact.jpg",
    previewFile: "Preview Real-world relevance Community impact project.pdf",
    category: "literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 52,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-kitchen-math",
    name: "Kitchen Math & Meal Planning Challenge",
    slug: "kitchen-math-challenge",
    description:
      "Go beyond recipes — plan meals for a week, calculate grocery costs, compare unit prices, adjust portions, and manage a food budget. Real-world maths that happens in the kitchen, at the shop, and around the dinner table.",
    shortDescription:
      "Plan meals, calculate costs, and manage a food budget — real-world kitchen maths.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/kitchen-math-challenge.jpg",
    previewFile: "Preview Real-world relevance Kitchen math & meal planning challenge.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 53,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-media-info-check",
    name: "Media & Info Check",
    slug: "media-info-check",
    description:
      "Critical thinking activities that teach kids to evaluate information, spot bias, check sources, and think critically about what they see online. In a world of misinformation, these are essential skills — and they're best learned through practice, not lectures.",
    shortDescription:
      "Critical thinking activities — evaluate sources, spot bias, and check facts.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/media-info-check.jpg",
    previewFile: "Preview Real-world relevance Media & info check.pdf",
    category: "critical-thinking",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 54,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-micro-business",
    name: "Micro-Business Challenge",
    slug: "micro-business",
    description:
      "Guided activities to help your child plan, launch, and run a simple real business. From choosing a product to setting prices, marketing, tracking income, and reflecting on what they learned. Entrepreneurship skills through hands-on experience.",
    shortDescription:
      "Plan, launch, and run a real micro-business — entrepreneurship for kids.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/micro-business.jpg",
    previewFile: "Preview Real-world relevance Micro-business challenge.pdf",
    category: "critical-thinking",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 55,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-problem-solver",
    name: "Problem-Solver Studio",
    slug: "problem-solver",
    description:
      "Design thinking challenges that teach kids to identify problems, brainstorm solutions, prototype, test, and iterate. Real-world problem-solving skills applied to everyday life — from improving a family routine to designing a better lunchbox.",
    shortDescription:
      "Design thinking challenges — identify problems, brainstorm, prototype, and iterate.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/problem-solver.jpg",
    previewFile: "Preview Real-world relevance Problem-solver studio.pdf",
    category: "critical-thinking",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 56,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-smart-shopper",
    name: "Smart Shopper Lab",
    slug: "smart-shopper",
    description:
      "Activities that teach kids to be critical, informed consumers. Compare prices, read labels, spot marketing tricks, calculate value, and make smart purchasing decisions. Financial literacy meets critical thinking — skills they'll use for life.",
    shortDescription:
      "Learn to compare prices, read labels, and make smart purchasing decisions.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/smart-shopper.jpg",
    previewFile: "Preview Real-world relevance Smart shopper lab.pdf",
    category: "real-world-math",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 57,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-time-energy-planner",
    name: "Time & Energy Planner",
    slug: "time-energy-planner",
    description:
      "Help your child learn to manage their time and energy effectively. Activities include building weekly schedules, tracking energy levels, prioritising tasks, setting goals, and reflecting on what works. Self-management skills that schools rarely teach.",
    shortDescription:
      "Build schedules, track energy, and learn self-management — essential life skills.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/time-energy-planner.jpg",
    previewFile: "Preview Real-world relevance Time & energy planner.pdf",
    category: "self-management",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 58,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-travel-day",
    name: "Travel Day Itinerary Challenge",
    slug: "travel-day",
    description:
      "Challenge your child to plan a real travel day from start to finish. Research destinations, compare transport options, calculate budgets, build itineraries, and navigate logistics. Geography, maths, and decision-making wrapped in an exciting real-world project.",
    shortDescription:
      "Plan a real travel day — research, budget, and build a complete itinerary.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/travel-day.jpg",
    previewFile: "Preview Real-world relevance Travel Day itinerary challenge.pdf",
    category: "critical-thinking",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 59,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-write-like-pro",
    name: "Write It Like a Pro",
    slug: "write-like-a-pro",
    description:
      "Real-world writing challenges that go beyond essays. Kids write emails, create social media posts, draft persuasive letters, design infographics with captions, and communicate for real audiences. Writing skills that matter in the real world, practised in context.",
    shortDescription:
      "Real-world writing challenges — emails, letters, persuasive writing, and communication.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/write-like-a-pro.jpg",
    previewFile: "Preview Real-world relevance Write it like a pro.pdf",
    category: "literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 60,
    active: true,
    createdAt: new Date("2025-01-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // AI & DIGITAL LITERACY
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-ai-basics",
    name: "AI Basics: Myths, Facts & Smart Rules",
    slug: "ai-basics",
    description:
      "Help kids understand what AI actually is, what it isn't, and how to use it responsibly. Activities cover how AI works, common myths vs reality, healthy and useful AI interactions, and setting smart rules for AI use at home. The foundation for everything else in the AI series.",
    shortDescription:
      "What AI actually is, common myths vs facts, and smart rules for responsible use.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/ai-basics.jpg",
    previewFile: "Preview AI + Digital Literacy - AI BASICS MYTHS, FACTS & SMART RULES.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 70,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-algorithm-awareness",
    name: "Algorithm Awareness: Why Am I Seeing This?",
    slug: "algorithm-awareness",
    description:
      "Teach kids how algorithms shape what they see online — and what they don't. Activities explore recommendation systems, filter bubbles, engagement tricks, and how to take back control of their feed. Critical digital literacy for the attention economy.",
    shortDescription:
      "Understand how algorithms shape what you see online — and take back control.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/algorithm-awareness.jpg",
    previewFile: "Preview AI + Digital Literacy - ALGORITHM AWARENESS WHY AM I SEEING THIS.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 71,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-bias-fairness",
    name: "Bias & Fairness Lab",
    slug: "bias-fairness-lab",
    description:
      "Explore how AI can be unfair — and what to do about it. Kids investigate real examples of AI bias, examine who gets left out, test for fairness in prompts and outputs, and design better AI choices. Ethics and critical thinking through hands-on investigation.",
    shortDescription:
      "Investigate AI bias — who gets left out, why, and how to design for fairness.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/bias-fairness-lab.jpg",
    previewFile: "Preview AI + Digital Literacy - BIAS & FAIRNESS LAB.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 72,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-build-ai-helper",
    name: "Build Your Own AI Helper",
    slug: "build-ai-helper",
    description:
      "Design and plan your own AI helper — what it does, how it works, what data it needs, and what ethical rules it follows. Kids think through the entire process of creating a useful AI tool, from concept to safety considerations. No coding required — this is about thinking, not programming.",
    shortDescription:
      "Design an AI helper from concept to ethics — creative tech thinking, no coding needed.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/build-ai-helper.jpg",
    previewFile: "Preview AI + Digital Literacy - BUILD YOUR OWN AI HELPER.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 73,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-create-with-ai",
    name: "Create With AI, Ethically",
    slug: "create-with-ai",
    description:
      "Explore creative AI tools responsibly. Kids learn to use AI for writing, art, and brainstorming while understanding copyright, attribution, and the difference between using AI as a tool vs letting it do the thinking. Creativity enhanced by technology, guided by ethics.",
    shortDescription:
      "Use AI for creative projects responsibly — copyright, attribution, and ethical creation.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/create-with-ai.jpg",
    previewFile: "Preview AI + Digital Literacy - CREATE WITH AI, ETHICALLY.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 74,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-deepfake-spotter",
    name: "Deepfake & Manipulation Spotter",
    slug: "deepfake-spotter",
    description:
      "Teach kids to spot manipulated images, videos, and content. Activities cover deepfake detection, image verification, \"pause before sharing\" skills, and how to evaluate whether what they're seeing is real. Essential media literacy for the AI age.",
    shortDescription:
      "Spot deepfakes and manipulated content — essential media literacy for the AI age.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/deepfake-spotter.jpg",
    previewFile: "Preview AI + Digital Literacy - DEEPFAKE & MANIPULATION SPOTTER.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 75,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-hallucination-detective",
    name: "Hallucination Detective",
    slug: "hallucination-detective",
    description:
      "Investigation activities that teach kids to spot when AI gets things wrong. Kids learn about AI hallucinations, practise verifying AI outputs, understand why AI makes confident mistakes, and develop the habit of always checking before trusting. Trust, verify, and improve.",
    shortDescription:
      "Spot when AI gets things wrong — verify, fact-check, and build critical trust.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/hallucination-detective.jpg",
    previewFile: "Preview AI + Digital Literacy - HALLUCINATION DETECTIVE.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 76,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-healthy-tech",
    name: "Healthy Tech & AI Boundaries Plan",
    slug: "healthy-tech-boundaries",
    description:
      "Help your child create a personal technology and AI boundaries plan. Activities cover screen time awareness, digital wellbeing, setting healthy limits, managing notifications, and building a balanced relationship with technology. Self-regulation skills for the digital age.",
    shortDescription:
      "Create a personal tech boundaries plan — digital wellbeing and self-regulation.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/healthy-tech-boundaries.jpg",
    previewFile: "Preview AI + Digital Literacy - HEALTHY TECH & AI BOUNDARIES PLAN.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 77,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-privacy-footprint",
    name: "Privacy & Digital Footprint Map",
    slug: "privacy-footprint",
    description:
      "Map your digital footprint and understand online privacy. Kids discover what personal data they share, how data trails work, smart sharing practices, and how to protect their personal information. Practical privacy education, not paranoia.",
    shortDescription:
      "Map your digital footprint — understand data, privacy, and smart sharing.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/privacy-footprint.jpg",
    previewFile: "Preview AI + Digital Literacy - PRIVACY & DIGITAL FOOTPRINT MAP.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 78,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-prompt-coach",
    name: "Prompt Like a Coach",
    slug: "prompt-like-a-coach",
    description:
      "Teach kids to get better results from AI by writing better prompts. Activities cover prompt structure, asking better questions, healthy AI use (not copying), and learning to guide AI rather than just accepting its first answer. The skill that makes all other AI skills more powerful.",
    shortDescription:
      "Write better AI prompts — ask better questions and guide AI like a coach.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/prompt-like-a-coach.jpg",
    previewFile: "Preview AI + Digital Literacy - PROMPT LIKE A COACH.pdf",
    category: "ai-literacy",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 9–14",
    sortOrder: 79,
    active: true,
    createdAt: new Date("2025-01-01"),
  },

  // ─────────────────────────────────────────────────────────────
  // LIFE SKILLS
  // ─────────────────────────────────────────────────────────────
  {
    id: "fb-skills-map",
    name: "The Future-Ready Skills Map",
    slug: "future-ready-skills-map",
    description:
      "A comprehensive 42-page parent guide to the 10 skills that matter most for your child's future — from emotional intelligence and critical thinking to AI literacy and life skills. Organised into three age bands (0–6, 6–11, 11–14+), each section includes what to develop, what mastery looks like, hands-on activities, a sample week, and a one-page skills-at-a-glance overview.",
    shortDescription:
      "A 42-page parent guide to the 10 skills that matter most — with activities, milestones, and sample weeks for ages 0–14+.",
    priceCents: 999,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/future-ready-skills-map.jpg",
    previewFile: "Preview The future-ready skills map.pdf",
    category: "life-skills",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 0–14+",
    sortOrder: 90,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-small-business",
    name: "My Small Business Project",
    slug: "my-small-business-project",
    description:
      "A complete project guide for kids to plan and run their own small business. From brainstorming ideas and researching markets to creating products, setting prices, designing marketing, and tracking profits. Entrepreneurship, financial literacy, and creativity all in one hands-on project.",
    shortDescription:
      "Plan and run a real small business — entrepreneurship, marketing, and financial literacy.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/my-small-business-project.jpg",
    previewFile: "Preview My small business project.pdf",
    category: "life-skills",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 8–14",
    sortOrder: 91,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "fb-time-capsule",
    name: "Time Capsule",
    slug: "time-capsule",
    description:
      "A creative time capsule project that captures who your child is right now. Guided prompts for writing letters to their future self, collecting meaningful items, recording favourites, and reflecting on growth. A beautiful keepsake project that doubles as a writing and self-awareness activity.",
    shortDescription:
      "Capture who your child is right now — guided prompts for a meaningful time capsule.",
    priceCents: 499,
    compareAtPriceCents: null,
    stripePriceId: "",
    blobUrl: "",
    imageUrl: "/products/time-capsule.jpg",
    previewFile: "Preview Time Capsule.pdf",
    category: "life-skills",
    isBundle: false,
    bundleProductIds: null,
    activityCount: null,
    ageRange: "Ages 6–14",
    sortOrder: 92,
    active: true,
    createdAt: new Date("2025-01-01"),
  },
];

export function getFallbackProductBySlug(slug: string): FallbackProduct | null {
  return fallbackProducts.find((p) => p.slug === slug) ?? null;
}

export function getFallbackProducts(): FallbackProduct[] {
  return fallbackProducts.filter((p) => p.active);
}

export function searchFallbackProducts(query: string): FallbackProduct[] {
  const q = query.toLowerCase();
  return fallbackProducts.filter(
    (p) =>
      p.active &&
      (p.name.toLowerCase().includes(q) ||
        p.shortDescription.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q)),
  );
}

export function filterByAge<T extends { ageRange?: string | null }>(
  products: T[],
  minAge: number,
): T[] {
  return products.filter((p) => {
    if (!p.ageRange) return true;
    // Extract first number from ageRange like "Ages 4–14" → 4
    const match = p.ageRange.match(/(\d+)/);
    if (!match) return true;
    const productMinAge = parseInt(match[1], 10);
    return productMinAge <= minAge;
  });
}

export function getProductCounts(products: { category: string }[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const p of products) {
    counts[p.category] = (counts[p.category] || 0) + 1;
  }
  return counts;
}
