/**
 * AUTO-GENERATED by scripts/generate-skills-lib.mjs. Do not edit by hand.
 *
 * The 10 top-level Skill Families (used in the /shop filter) and the canonical
 * skill names per product slug (extracted by OCR from the actual activity PDFs
 * via scripts/extract-pdf-skills.mjs and reconciled by build-skills-taxonomy.mjs).
 */

export interface SkillFamily {
  /** URL-safe slug, e.g. "critical-thinking-and-reasoning". */
  slug: string;
  /** Human-facing label, e.g. "Critical Thinking & Reasoning". */
  name: string;
  /** How many activities are tagged with this family (for UI display). */
  count: number;
}

export const SKILL_FAMILIES: readonly SkillFamily[] = [
  { slug: "critical-thinking-and-reasoning", name: "Critical Thinking & Reasoning", count: 63 },
  { slug: "communication-and-writing", name: "Communication & Writing", count: 55 },
  { slug: "planning-and-self-management", name: "Planning & Self-Management", count: 38 },
  { slug: "empathy-and-people", name: "Empathy & People", count: 25 },
  { slug: "math-and-money", name: "Math & Money", count: 20 },
  { slug: "creativity-and-making", name: "Creativity & Making", count: 19 },
  { slug: "nature-and-science", name: "Nature & Science", count: 19 },
  { slug: "entrepreneurship-and-money", name: "Entrepreneurship & Money", count: 16 },
  { slug: "tech-and-digital", name: "Tech & Digital", count: 11 },
  { slug: "world-and-geography", name: "World & Geography", count: 8 },
];

export interface ProductSkills {
  /** Canonical skill names (display on the product page). */
  canonical: string[];
  /** Skill family slugs (used by the filter). */
  families: string[];
}

/**
 * Map of product slug → extracted skill data. Activities not in this map
 * (card packs, bundles, parent guides) keep their existing skillTags from
 * `lib/product-descriptions.ts` and are not filterable by family.
 */
export const productSkills: Record<string, ProductSkills> = {
  "adventure-story-map": { canonical: ["Creative Thinking","Observation","Spatial Thinking","Writing"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","nature-and-science"] },
  "ai-basics": { canonical: ["AI Literacy","Communication","Critical Thinking","Decision-Making","Digital Citizenship"], families: ["communication-and-writing","critical-thinking-and-reasoning","tech-and-digital"] },
  "algorithm-awareness": { canonical: ["Critical Thinking","Decision-Making","Digital Literacy","Reflection","Self-Direction"], families: ["critical-thinking-and-reasoning","planning-and-self-management","tech-and-digital"] },
  "backyard-campout-planner": { canonical: ["Math","Number Sense"], families: ["math-and-money"] },
  "bias-fairness-lab": { canonical: ["AI Literacy","Communication","Critical Thinking","Decision-Making","Empathy"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","tech-and-digital"] },
  "board-game-studio": { canonical: ["Creative Thinking","Design Thinking","Math"], families: ["creativity-and-making","math-and-money"] },
  "brand-builder": { canonical: ["Art","Creative Thinking","Critical Thinking","Storytelling"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning"] },
  "budget-challenge": { canonical: ["Budgeting","Communication","Decision-Making","Number Sense","Planning","Problem-Solving"], families: ["communication-and-writing","critical-thinking-and-reasoning","entrepreneurship-and-money","math-and-money","planning-and-self-management"] },
  "build-ai-helper": { canonical: ["AI Literacy","Communication","Online Safety & Privacy","Problem-Solving","Reflection"], families: ["communication-and-writing","critical-thinking-and-reasoning","tech-and-digital"] },
  "business-failure-lab": { canonical: ["Adaptability","Communication","Critical Thinking","Problem-Solving","Resilience","Systems Thinking"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","planning-and-self-management"] },
  "clothing-swap-thrift-math": { canonical: ["Critical Thinking","Financial Literacy","Number Sense","Percentages"], families: ["critical-thinking-and-reasoning","entrepreneurship-and-money","math-and-money"] },
  "community-impact": { canonical: ["Communication","Planning","Reflection"], families: ["communication-and-writing","critical-thinking-and-reasoning","planning-and-self-management"] },
  "community-service-business": { canonical: ["Communication","Observation","Planning","Problem-Solving","Resilience"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","nature-and-science","planning-and-self-management"] },
  "community-tour-guide": { canonical: ["Audience Awareness","Confidence","Organisation","Public Speaking","Research","Storytelling"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","planning-and-self-management"] },
  "create-with-ai": { canonical: ["Communication","Creative Thinking","Decision-Making","Digital Citizenship"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","tech-and-digital"] },
  "creature-habitat": { canonical: ["Communication","Engineering","Problem-Solving","Science"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","nature-and-science"] },
  "cultural-celebration-journal": { canonical: ["Communication","Critical Thinking","Cultural Awareness","Empathy","Research"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","world-and-geography"] },
  "currency-market-math": { canonical: ["Critical Thinking","Financial Literacy","Math","Problem-Solving"], families: ["critical-thinking-and-reasoning","entrepreneurship-and-money","math-and-money"] },
  "customer-discovery": { canonical: ["Communication","Critical Thinking","Empathy","Entrepreneurship","Research"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","entrepreneurship-and-money"] },
  "decision-lab": { canonical: ["Communication","Critical Thinking","Decision-Making","Empathy"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people"] },
  "deepfake-spotter": { canonical: ["Decision-Making","Digital Citizenship","Emotional Regulation","Observation"], families: ["critical-thinking-and-reasoning","empathy-and-people","nature-and-science","planning-and-self-management","tech-and-digital"] },
  "directions-challenge": { canonical: ["Empathy","Observation","Problem-Solving"], families: ["critical-thinking-and-reasoning","empathy-and-people","nature-and-science"] },
  "emergency-ready": { canonical: ["Communication","Critical Thinking","Executive Functioning","Life Skills","Planning"], families: ["communication-and-writing","critical-thinking-and-reasoning","planning-and-self-management"] },
  "everyday-life-comparison": { canonical: ["Communication","Critical Thinking","Cultural Awareness","Empathy","Observation"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","nature-and-science","world-and-geography"] },
  "everyday-redesign": { canonical: ["Communication","Critical Thinking","Design Thinking","Life Skills","Systems Thinking"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","planning-and-self-management"] },
  "family-debate-night": { canonical: ["Critical Thinking","Listening","Persuasion","Public Speaking"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people"] },
  "family-electricity-audit": { canonical: ["Number Sense","Organisation","Percentages","Problem-Solving"], families: ["critical-thinking-and-reasoning","math-and-money","planning-and-self-management"] },
  "family-recipe-book": { canonical: ["Organisation","Writing"], families: ["communication-and-writing","planning-and-self-management"] },
  "farmers-market-challenge": { canonical: ["Communication","Financial Literacy","Math","Number Sense","Planning","Pricing & Sales"], families: ["communication-and-writing","entrepreneurship-and-money","math-and-money","planning-and-self-management"] },
  "fix-it-detective": { canonical: ["Critical Thinking","Life Skills","Planning","Problem-Solving","Research"], families: ["critical-thinking-and-reasoning","planning-and-self-management"] },
  "garage-sale-math": { canonical: ["Number Sense","Pricing & Sales"], families: ["entrepreneurship-and-money","math-and-money"] },
  "garden-plot-planner": { canonical: ["Math","Number Sense","Observation","Research","Spatial Thinking"], families: ["critical-thinking-and-reasoning","math-and-money","nature-and-science"] },
  "hallucination-detective": { canonical: ["Critical Thinking","Writing"], families: ["communication-and-writing","critical-thinking-and-reasoning"] },
  "healthy-tech-boundaries": { canonical: ["Decision-Making","Digital Citizenship","Engineering","Reflection","Self-Direction"], families: ["creativity-and-making","critical-thinking-and-reasoning","planning-and-self-management","tech-and-digital"] },
  "imaginary-world": { canonical: ["Creative Thinking","Storytelling","Systems Thinking"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning"] },
  "invent-a-sport": { canonical: ["Communication","Design Thinking","Ethics","Math"], families: ["communication-and-writing","creativity-and-making","empathy-and-people","math-and-money","tech-and-digital"] },
  "investor-pitch": { canonical: ["Communication","Critical Thinking","Decision-Making"], families: ["communication-and-writing","critical-thinking-and-reasoning"] },
  "kinetic-sculpture": { canonical: ["Art","Communication","Engineering","Problem-Solving"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning"] },
  "kitchen-math-challenge": { canonical: ["Budgeting","Math","Planning","Problem-Solving","Self-Direction"], families: ["critical-thinking-and-reasoning","entrepreneurship-and-money","math-and-money","planning-and-self-management"] },
  "local-language-mission": { canonical: ["Communication","Confidence","Critical Thinking","Cultural Awareness","Observation"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","nature-and-science","planning-and-self-management","world-and-geography"] },
  "market-stall-pitch": { canonical: ["Audience Awareness","Confidence","Creative Thinking","Entrepreneurship","Persuasion"], families: ["communication-and-writing","creativity-and-making","empathy-and-people","entrepreneurship-and-money","planning-and-self-management"] },
  "marketing-campaign": { canonical: ["Adaptability","Creative Thinking","Critical Thinking","Design Thinking","Persuasion"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","planning-and-self-management"] },
  "media-info-check": { canonical: ["Communication","Critical Thinking","Digital Literacy","Emotional Regulation"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","planning-and-self-management","tech-and-digital"] },
  "micro-business": { canonical: ["Communication","Financial Literacy","Problem-Solving","Research","Resilience"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","entrepreneurship-and-money","math-and-money","planning-and-self-management"] },
  "mini-magazine-creator": { canonical: ["Audience Awareness","Research","Writing"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people"] },
  "mini-movie": { canonical: ["Planning","Problem-Solving","Public Speaking","Storytelling"], families: ["communication-and-writing","critical-thinking-and-reasoning","planning-and-self-management"] },
  "my-review-column": { canonical: ["Audience Awareness","Critical Thinking","Writing"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people"] },
  "nature-geography-field-study": { canonical: ["Art","Critical Thinking","Geography","Observation","Science"], families: ["creativity-and-making","critical-thinking-and-reasoning","nature-and-science","world-and-geography"] },
  "neighbourhood-interview": { canonical: ["Communication","Empathy","Listening"], families: ["communication-and-writing","empathy-and-people"] },
  "neighbourhood-problem-spotter": { canonical: ["Communication","Critical Thinking","Problem-Solving","Research"], families: ["communication-and-writing","critical-thinking-and-reasoning"] },
  "outdoor-survival-planner": { canonical: ["Critical Thinking","Nature Connection","Planning","Problem-Solving","Resilience"], families: ["critical-thinking-and-reasoning","empathy-and-people","nature-and-science","planning-and-self-management"] },
  "pack-like-a-pro": { canonical: ["Adaptability","Critical Thinking","Decision-Making","Life Skills","Planning"], families: ["critical-thinking-and-reasoning","planning-and-self-management"] },
  "party-planner-math": { canonical: ["Financial Literacy","Number Sense"], families: ["entrepreneurship-and-money","math-and-money"] },
  "people-stories-interview": { canonical: ["Communication","Confidence","Cultural Awareness","Empathy","Listening"], families: ["communication-and-writing","empathy-and-people","planning-and-self-management","world-and-geography"] },
  "pricing-experiment": { canonical: ["Communication","Critical Thinking","Financial Literacy","Problem-Solving","Research"], families: ["communication-and-writing","critical-thinking-and-reasoning","entrepreneurship-and-money","math-and-money"] },
  "privacy-footprint": { canonical: ["Critical Thinking","Decision-Making","Digital Citizenship","Online Safety & Privacy"], families: ["critical-thinking-and-reasoning","tech-and-digital"] },
  "problem-solver": { canonical: ["Communication","Critical Thinking","Planning","Problem-Solving"], families: ["communication-and-writing","critical-thinking-and-reasoning","planning-and-self-management"] },
  "product-design-lab": { canonical: ["Communication","Creative Thinking","Critical Thinking","Design Thinking","Executive Functioning"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","planning-and-self-management"] },
  "prompt-like-a-coach": { canonical: ["Communication","Critical Thinking","Writing"], families: ["communication-and-writing","critical-thinking-and-reasoning"] },
  "road-trip-calculator": { canonical: ["Budgeting","Math","Planning"], families: ["entrepreneurship-and-money","math-and-money","planning-and-self-management"] },
  "rube-goldberg-machine": { canonical: ["Communication","Engineering","Problem-Solving","Science"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","nature-and-science"] },
  "savings-goal-tracker": { canonical: ["Budgeting","Data & Graphs","Decision-Making","Number Sense","Percentages"], families: ["critical-thinking-and-reasoning","entrepreneurship-and-money","math-and-money"] },
  "scavenger-hunt-designer": { canonical: ["Communication","Creative Thinking","Planning","Problem-Solving"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","planning-and-self-management"] },
  "shark-tank-pitch": { canonical: ["Financial Literacy","Persuasion","Public Speaking","Resilience"], families: ["communication-and-writing","empathy-and-people","entrepreneurship-and-money","math-and-money","planning-and-self-management"] },
  "smart-shopper": { canonical: ["Communication","Critical Thinking","Decision-Making","Financial Literacy","Media Literacy"], families: ["communication-and-writing","critical-thinking-and-reasoning","entrepreneurship-and-money","math-and-money","tech-and-digital"] },
  "sports-stats-lab": { canonical: ["Organisation","Percentages"], families: ["math-and-money","planning-and-self-management"] },
  "street-explorer-map-maker": { canonical: ["Communication","Critical Thinking","Geography","Observation","Spatial Thinking"], families: ["communication-and-writing","critical-thinking-and-reasoning","nature-and-science","world-and-geography"] },
  "supply-chain-detective": { canonical: ["Communication","Geography","Problem-Solving","Research","Systems Thinking"], families: ["communication-and-writing","critical-thinking-and-reasoning","nature-and-science","world-and-geography"] },
  "survival-base": { canonical: ["Communication","Creative Thinking","Planning","Science"], families: ["communication-and-writing","creativity-and-making","nature-and-science","planning-and-self-management"] },
  "swap-day-challenge": { canonical: ["Life Skills","Planning"], families: ["planning-and-self-management"] },
  "theme-park": { canonical: ["Communication","Engineering","Entrepreneurship","Spatial Thinking"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","entrepreneurship-and-money","nature-and-science"] },
  "time-energy-planner": { canonical: ["Emotional Regulation","Executive Functioning","Planning","Problem-Solving"], families: ["critical-thinking-and-reasoning","empathy-and-people","planning-and-self-management"] },
  "trail-guide-creator": { canonical: ["Audience Awareness","Observation","Organisation","Writing"], families: ["communication-and-writing","critical-thinking-and-reasoning","empathy-and-people","nature-and-science","planning-and-self-management"] },
  "transport-navigation-challenge": { canonical: ["Critical Thinking","Geography","Math","Observation","Problem-Solving","Self-Direction"], families: ["critical-thinking-and-reasoning","math-and-money","nature-and-science","planning-and-self-management","world-and-geography"] },
  "travel-day": { canonical: ["Communication","Decision-Making","Planning","Problem-Solving"], families: ["communication-and-writing","critical-thinking-and-reasoning","planning-and-self-management"] },
  "travel-reflection-postcards": { canonical: ["Communication","Observation","Reflection","Writing"], families: ["communication-and-writing","critical-thinking-and-reasoning","nature-and-science"] },
  "what-if-scenario-lab": { canonical: ["Communication","Creative Thinking","Critical Thinking","Planning","Research"], families: ["communication-and-writing","creativity-and-making","critical-thinking-and-reasoning","planning-and-self-management"] },
  "world-food-detective": { canonical: ["Communication","Critical Thinking","Observation","Research"], families: ["communication-and-writing","critical-thinking-and-reasoning","nature-and-science"] },
  "write-like-a-pro": { canonical: ["Audience Awareness","Confidence","Persuasion"], families: ["communication-and-writing","empathy-and-people","planning-and-self-management"] },
};

/** Look up skills for a product slug. Returns null if the activity wasn't
 *  extracted (e.g. it's a card pack or bundle). */
export function getProductSkills(slug: string): ProductSkills | null {
  return productSkills[slug] || null;
}

/** Find a family by slug. */
export function getFamily(slug: string): SkillFamily | undefined {
  return SKILL_FAMILIES.find((f) => f.slug === slug);
}
