import { loadEnvConfig } from '@next/env';
loadEnvConfig(process.cwd());

import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { products } from '../lib/db/schema';

async function seed() {
  if (!process.env.DATABASE_URL) {
    console.error('DATABASE_URL is required. Set it in .env.local');
    process.exit(1);
  }

  const sql = neon(process.env.DATABASE_URL);
  const db = drizzle(sql);

  console.log('Seeding products...');

  // Product data matches slugs from fallback-products.ts.
  // Run `npm run stripe:sync` first to get real stripePriceIds.
  const productData = [
    // === OUTDOOR LEARNING - Seasonal packs (sortOrder 10-13) ===
    { name: 'Spring Outdoor Learning Pack', slug: 'spring-outdoor-pack', description: '20 outdoor activities for spring.', shortDescription: '20 spring outdoor activities.', priceCents: 1499, compareAtPriceCents: null, stripePriceId: 'price_1TFcTQAMzOBftCntYvoO0bs3', blobUrl: '', imageUrl: '/products/spring-outdoor-pack.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: 20, ageRange: 'Ages 6\u201314', sortOrder: 10, active: false },
    { name: 'Summer Outdoor Learning Pack', slug: 'summer-outdoor-pack', description: '20 summer activities for families on the move.', shortDescription: '20 summer outdoor activities.', priceCents: 1499, compareAtPriceCents: null, stripePriceId: 'price_1TFcTRAMzOBftCntcBe5IbiX', blobUrl: '', imageUrl: '/products/summer-outdoor-pack.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: 20, ageRange: 'Ages 6\u201314', sortOrder: 11, active: false },
    { name: 'Fall Outdoor Learning Pack', slug: 'fall-outdoor-pack', description: '20 autumn activities for observation and creative skills.', shortDescription: '20 fall outdoor activities.', priceCents: 1499, compareAtPriceCents: null, stripePriceId: 'price_1TFcTRAMzOBftCntOiiukmBd', blobUrl: '', imageUrl: '/products/fall-outdoor-pack.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: 20, ageRange: 'Ages 6\u201314', sortOrder: 12, active: false },
    { name: 'Winter Outdoor Learning Pack', slug: 'winter-outdoor-pack', description: '20 winter activities for indoor and outdoor adventures.', shortDescription: '20 winter activities.', priceCents: 1499, compareAtPriceCents: null, stripePriceId: 'price_1TFcTSAMzOBftCntqOOGzx0P', blobUrl: '', imageUrl: '/products/winter-outdoor-pack.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: 20, ageRange: 'Ages 6\u201314', sortOrder: 13, active: false },

    // === OUTDOOR LEARNING (sortOrder 20–26) ===
    { name: 'My Nature Journal', slug: 'nature-journal-walks', description: 'A guided nature journal with prompts for sketching, writing, and outdoor observation.', shortDescription: 'Guided nature journal for outdoor observation.', priceCents: 799, compareAtPriceCents: null, stripePriceId: 'price_1TFcTSAMzOBftCntNAM1nnp4', blobUrl: '', imageUrl: '/products/nature-journal-walks.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 20, active: true },
    { name: 'Nature Walk Task Cards', slug: 'nature-walk-task-cards', description: 'Structured observation prompts for any outdoor walk.', shortDescription: 'Structured nature observation prompts.', priceCents: 799, compareAtPriceCents: null, stripePriceId: 'price_1TFcTTAMzOBftCnt7T0mraep', blobUrl: '', imageUrl: '/products/nature-walk-task-cards.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 21, active: true },
    { name: 'Nature Choice Boards', slug: 'nature-choice-boards', description: 'Pick-your-own-adventure nature activity boards.', shortDescription: 'Pick-your-own nature activity boards.', priceCents: 799, compareAtPriceCents: null, stripePriceId: 'price_1TFcTTAMzOBftCntVkFfPzek', blobUrl: '', imageUrl: '/products/nature-choice-boards.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 22, active: true },
    { name: 'Outdoor Learning Missions', slug: 'outdoor-learning-missions', description: 'Mission-based outdoor challenges for curious explorers.', shortDescription: 'Mission-based outdoor challenges.', priceCents: 799, compareAtPriceCents: null, stripePriceId: 'price_1TFcTUAMzOBftCntCKLS3VQS', blobUrl: '', imageUrl: '/products/outdoor-learning-missions.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 23, active: true },
    { name: 'Outdoor STEM Challenge Cards', slug: 'outdoor-stem-challenges', description: '20 outdoor STEM challenges using the natural world.', shortDescription: '20 outdoor STEM challenges.', priceCents: 799, compareAtPriceCents: null, stripePriceId: 'price_1TFcTUAMzOBftCntt5p1Oosa', blobUrl: '', imageUrl: '/products/outdoor-stem-challenges.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: 20, ageRange: 'Ages 6\u201314', sortOrder: 24, active: true },
    { name: 'Land Art Challenge Cards', slug: 'land-art-challenges', description: '15 land art challenges using natural materials.', shortDescription: '15 land art challenges.', priceCents: 799, compareAtPriceCents: null, stripePriceId: 'price_1TFcTUAMzOBftCntKXDbLWvQ', blobUrl: '', imageUrl: '/products/land-art-challenges.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: 15, ageRange: 'Ages 6\u201314', sortOrder: 25, active: true },
    { name: 'Nature Crafts for Kids', slug: 'nature-crafts', description: 'Hands-on crafting projects using natural materials.', shortDescription: 'Nature craft projects.', priceCents: 799, compareAtPriceCents: null, stripePriceId: 'price_1TFcTVAMzOBftCntMzWbHkjq', blobUrl: '', imageUrl: '/products/nature-crafts.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 26, active: true },

    // === CREATIVITY ANYWHERE (sortOrder 30–40) ===
    { name: 'Board Game Studio', slug: 'board-game-studio', description: 'Design, build, and playtest an original board game.', shortDescription: 'Design and build an original board game.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTWAMzOBftCntCEdcAPUE', blobUrl: '', imageUrl: '/products/board-game-studio.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 31, active: true },
    { name: 'Rube Goldberg Machine', slug: 'rube-goldberg-machine', description: 'Build an absurdly complicated machine to do something simple.', shortDescription: 'Build an absurd chain-reaction machine.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTWAMzOBftCnt2HICs5Uj', blobUrl: '', imageUrl: '/products/rube-goldberg-machine.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 32, active: true },
    { name: 'Build a Survival Base', slug: 'survival-base', description: 'Plan and build a survival base for an imaginary expedition.', shortDescription: 'Build a survival base for an expedition.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTXAMzOBftCnt2xp5XUtF', blobUrl: '', imageUrl: '/products/survival-base.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 33, active: true },
    { name: 'Build an Imaginary World', slug: 'imaginary-world', description: 'Design an entire imaginary world.', shortDescription: 'Design an imaginary world.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTXAMzOBftCntLpxVnTiV', blobUrl: '', imageUrl: '/products/imaginary-world.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 34, active: true },
    { name: 'Create a Creature & Habitat', slug: 'creature-habitat', description: 'Design a new creature and build its habitat.', shortDescription: 'Design a creature and its habitat.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTXAMzOBftCntW0sHBYh3', blobUrl: '', imageUrl: '/products/creature-habitat.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 35, active: true },
    { name: 'Design a Theme Park', slug: 'theme-park', description: 'Create a theme park or adventure course from scratch.', shortDescription: 'Design a theme park from scratch.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTYAMzOBftCntmrRvbNvV', blobUrl: '', imageUrl: '/products/theme-park.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 36, active: true },
    { name: 'Create a Mini Movie', slug: 'mini-movie', description: 'Write, film, and edit a mini movie or stop-motion.', shortDescription: 'Write, film, and edit a mini movie.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTYAMzOBftCntIDZw27XK', blobUrl: '', imageUrl: '/products/mini-movie.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 37, active: true },
    { name: 'Invent a New Sport', slug: 'invent-a-sport', description: 'Create a new sport with original rules and scoring.', shortDescription: 'Invent a new sport from scratch.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTZAMzOBftCntKUnaOIk2', blobUrl: '', imageUrl: '/products/invent-a-sport.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 38, active: true },
    { name: 'Kinetic Sculpture', slug: 'kinetic-sculpture', description: 'Build a moving sculpture or art installation.', shortDescription: 'Build a kinetic sculpture.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTZAMzOBftCntETLFEzEA', blobUrl: '', imageUrl: '/products/kinetic-sculpture.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 39, active: true },
    { name: 'Build a Museum', slug: 'build-a-museum', description: 'Create a museum or interactive exhibit from scratch.', shortDescription: 'Build a museum or exhibit.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTaAMzOBftCntswLeOkPC', blobUrl: '', imageUrl: '/products/build-a-museum.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 40, active: true },

    // === REAL-WORLD MATH, COMMUNICATION, ENTREPRENEURSHIP & PLANNING (sortOrder 50–60) ===
    { name: 'Real-Life Budget Challenge', slug: 'budget-challenge', description: 'Plan a real day with a real budget. Research prices, handle surprise costs, and make trade-offs.', shortDescription: 'Real budgeting with real trade-offs.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTaAMzOBftCntcx3BoyC8', blobUrl: '', imageUrl: '/products/budget-challenge.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 110, active: true },
    { name: 'Community Impact Project', slug: 'community-impact', description: 'Pick a real neighbourhood problem, design a solution, build a plan, and do something about it.', shortDescription: 'Leadership through real community projects.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTbAMzOBftCntFStp6niy', blobUrl: '', imageUrl: '/products/community-impact.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 140, active: true },
    { name: 'Kitchen Math & Meal Planning Challenge', slug: 'kitchen-math-challenge', description: 'Plan a real meal, scale recipes, compare prices, and manage a grocery budget.', shortDescription: 'Real kitchen math and meal planning.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTbAMzOBftCntCTnW0gph', blobUrl: '', imageUrl: '/products/kitchen-math-challenge.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 111, active: true },
    { name: 'Media & Info Check', slug: 'media-info-check', description: 'Check reliability signals, find evidence, cross-check sources, and decide what is worth sharing.', shortDescription: 'Media literacy and critical thinking.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTcAMzOBftCntRkLHGW3w', blobUrl: '', imageUrl: '/products/media-info-check.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 80, active: true },
    { name: 'Micro-Business Challenge', slug: 'micro-business', description: 'Design a real business from scratch: idea, pricing, brand, marketing, and pitch.', shortDescription: 'Real entrepreneurship, not a simulation.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTcAMzOBftCntZcUkdoFu', blobUrl: '', imageUrl: '/products/micro-business.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 130, active: true },
    { name: 'Problem-Solver Studio', slug: 'problem-solver', description: 'Pick a real problem, brainstorm, prototype with household materials, test, and improve.', shortDescription: 'Design thinking for real problems.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTcAMzOBftCntgT52Nlxh', blobUrl: '', imageUrl: '/products/problem-solver.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 141, active: true },
    { name: 'Smart Shopper Lab', slug: 'smart-shopper', description: 'Compare two products, build a rubric, do cost-per-use math, spot marketing tricks, and write a recommendation.', shortDescription: 'Think before you spend.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTdAMzOBftCntoJjP3hy7', blobUrl: '', imageUrl: '/products/smart-shopper.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 112, active: true },
    { name: 'Time & Energy Planner', slug: 'time-energy-planner', description: 'Map energy patterns, match tasks to brain power, build a real plan, test it, and fix what doesn\u2019t work.', shortDescription: 'Self-management that actually sticks.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTdAMzOBftCntcxl1ggJF', blobUrl: '', imageUrl: '/products/time-energy-planner.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 142, active: true },
    { name: 'Travel Day Itinerary Challenge', slug: 'travel-day', description: 'Plan a real day trip: destination, budget, itinerary, curveball, and backup plan.', shortDescription: 'Plan a real day trip from scratch.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTeAMzOBftCntm89oK6q4', blobUrl: '', imageUrl: '/products/travel-day.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 143, active: true },
    { name: 'Write It Like a Pro', slug: 'write-like-a-pro', description: 'Pick a writing style, write for a real audience, edit, and revise. Six formats, one finished piece.', shortDescription: 'Real writing for real audiences.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTeAMzOBftCnti098zzDn', blobUrl: '', imageUrl: '/products/write-like-a-pro.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 120, active: true },


    // === AI & DIGITAL LITERACY (sortOrder 70–79) ===
    { name: 'AI Basics: Myths, Facts & Smart Rules', slug: 'ai-basics', description: 'Understand what AI is and how to use it wisely.', shortDescription: 'AI basics for kids.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTfAMzOBftCntjVdNUY97', blobUrl: '', imageUrl: '/products/ai-basics.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 70, active: true },
    { name: 'Algorithm Awareness', slug: 'algorithm-awareness', description: 'Understand how algorithms shape what we see online.', shortDescription: 'Algorithm awareness.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTfAMzOBftCntwgbhXS2c', blobUrl: '', imageUrl: '/products/algorithm-awareness.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 71, active: true },
    { name: 'Bias & Fairness Lab', slug: 'bias-fairness-lab', description: 'Explore bias in AI systems.', shortDescription: 'AI bias and fairness.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTgAMzOBftCnty4weOSMp', blobUrl: '', imageUrl: '/products/bias-fairness-lab.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 72, active: true },
    { name: 'Build Your Own AI Helper', slug: 'build-ai-helper', description: 'Design and prototype an AI tool.', shortDescription: 'Design an AI helper.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTgAMzOBftCnt2rlB7hz4', blobUrl: '', imageUrl: '/products/build-ai-helper.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 73, active: true },
    { name: 'Create with AI, Ethically', slug: 'create-with-ai', description: 'Use AI as a creative partner ethically.', shortDescription: 'Ethical AI creativity.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcThAMzOBftCnt9kE7d4xI', blobUrl: '', imageUrl: '/products/create-with-ai.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 74, active: true },
    { name: 'Deepfake & Manipulation Spotter', slug: 'deepfake-spotter', description: 'Spot manipulated media and deepfakes.', shortDescription: 'Deepfake detection skills.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcThAMzOBftCntXZfm3eqs', blobUrl: '', imageUrl: '/products/deepfake-spotter.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 75, active: true },
    { name: 'Hallucination Detective', slug: 'hallucination-detective', description: 'Catch when AI gets things wrong.', shortDescription: 'AI fact-checking skills.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcThAMzOBftCnthpXo1GG3', blobUrl: '', imageUrl: '/products/hallucination-detective.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 76, active: true },
    { name: 'Healthy Tech & AI Boundaries', slug: 'healthy-tech-boundaries', description: 'Build healthy boundaries with technology.', shortDescription: 'Healthy tech boundaries.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTiAMzOBftCntLgtp68hD', blobUrl: '', imageUrl: '/products/healthy-tech-boundaries.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 77, active: true },
    { name: 'Privacy & Digital Footprint Map', slug: 'privacy-footprint', description: 'Understand and manage your digital footprint.', shortDescription: 'Digital privacy skills.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTiAMzOBftCntrpKs7RZt', blobUrl: '', imageUrl: '/products/privacy-footprint.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 78, active: true },
    { name: 'Prompt Like a Coach', slug: 'prompt-like-a-coach', description: 'Master the art of talking to AI effectively.', shortDescription: 'AI prompt skills.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTjAMzOBftCntIAAq45jj', blobUrl: '', imageUrl: '/products/prompt-like-a-coach.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 79, active: true },

    // === REAL-WORLD MATH - New guides (sortOrder 100-109) ===
    { name: 'Backyard Campout Planner', slug: 'backyard-campout-planner', description: 'Plan a backyard campout from gear lists to meal prep and stargazing schedule.', shortDescription: 'Plan a backyard campout with real maths.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTjAMzOBftCntwUjIM1oY', blobUrl: '', imageUrl: '/products/backyard-campout-planner.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 100, active: true },
    { name: 'Clothing Swap & Thrift Math', slug: 'clothing-swap-thrift-math', description: 'Organise a clothing swap or thrift haul using real budgeting and value skills.', shortDescription: 'Thrift shopping and clothing swap maths.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTkAMzOBftCntI5TYd61b', blobUrl: '', imageUrl: '/products/clothing-swap-thrift-math.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 101, active: true },
    { name: 'Family Electricity Audit', slug: 'family-electricity-audit', description: 'Audit your household electricity use, calculate costs, and find ways to save.', shortDescription: 'Audit electricity use and calculate savings.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTkAMzOBftCntqGIpYdvv', blobUrl: '', imageUrl: '/products/family-electricity-audit.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 102, active: true },
    { name: 'Farmers Market Challenge', slug: 'farmers-market-challenge', description: 'Navigate a farmers market with a budget. Compare prices, make choices, and track spending.', shortDescription: 'Budget and shop at a farmers market.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTlAMzOBftCntP7s0G52o', blobUrl: '', imageUrl: '/products/farmers-market-challenge.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 103, active: true },
    { name: 'Garage Sale Math', slug: 'garage-sale-math', description: 'Plan, price, and run a garage sale using real-world maths and money skills.', shortDescription: 'Price, sell, and count change at a garage sale.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTlAMzOBftCntpm3NSf6g', blobUrl: '', imageUrl: '/products/garage-sale-math.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 104, active: true },
    { name: 'Garden Plot Planner', slug: 'garden-plot-planner', description: 'Design a garden plot using area, spacing, budgets, and seasonal planning.', shortDescription: 'Design a garden with real measurements and budgets.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTmAMzOBftCntEpC5zsfb', blobUrl: '', imageUrl: '/products/garden-plot-planner.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 105, active: true },
    { name: 'Party Planner Math', slug: 'party-planner-math', description: 'Plan a party from guest list to budget: food quantities, costs, and timing.', shortDescription: 'Plan a party with real budgets and quantities.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTmAMzOBftCntCKj30Y3C', blobUrl: '', imageUrl: '/products/party-planner-math.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 106, active: true },
    { name: 'Road Trip Calculator', slug: 'road-trip-calculator', description: 'Plan a road trip. Calculate distances, fuel costs, timing, and budgets.', shortDescription: 'Calculate distances, fuel, and budgets for a road trip.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTnAMzOBftCntxsHa6OHa', blobUrl: '', imageUrl: '/products/road-trip-calculator.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 107, active: true },
    { name: 'Savings Goal Tracker', slug: 'savings-goal-tracker', description: 'Set a savings goal and track progress with real money maths.', shortDescription: 'Set and track a real savings goal.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcTnAMzOBftCntIbm5J5xU', blobUrl: '', imageUrl: '/products/savings-goal-tracker.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 108, active: true },
    { name: 'Sports Stats Lab', slug: 'sports-stats-lab', description: 'Collect, analyse, and visualise real sports data: averages, percentages, and charts.', shortDescription: 'Analyse real sports stats and create charts.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TFcToAMzOBftCntrNhs4Q1o', blobUrl: '', imageUrl: '/products/sports-stats-lab.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 109, active: true },

    // === COMMUNICATION & WRITING - New guides (sortOrder 110-119) ===
    { name: 'Adventure Story Map', slug: 'adventure-story-map', description: 'Create a visual story map to plan and write your own adventure narrative.', shortDescription: 'Plan and write an adventure story.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/adventure-story-map.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 110, active: true },
    { name: 'Community Tour Guide', slug: 'community-tour-guide', description: 'Research and create a guided tour of your community.', shortDescription: 'Create a tour guide for your community.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/community-tour-guide.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 111, active: true },
    { name: 'Directions Challenge', slug: 'directions-challenge', description: 'Write clear, step-by-step directions and test if others can follow them.', shortDescription: 'Write and test clear directions.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/directions-challenge.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 112, active: true },
    { name: 'Family Debate Night', slug: 'family-debate-night', description: 'Prepare arguments, debate topics as a family, and practise persuasive speaking.', shortDescription: 'Family debate and persuasion skills.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/family-debate-night.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 113, active: true },
    { name: 'Family Recipe Book', slug: 'family-recipe-book', description: 'Document family recipes with clear instructions and family stories.', shortDescription: 'Create a family recipe book.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/family-recipe-book.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 114, active: true },
    { name: 'Market Stall Pitch', slug: 'market-stall-pitch', description: 'Create a persuasive pitch to sell a product or service at a market stall.', shortDescription: 'Practise persuasive selling.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/market-stall-pitch.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 115, active: true },
    { name: 'Mini Magazine Creator', slug: 'mini-magazine-creator', description: 'Write and design a mini magazine with articles, headlines, and illustrations.', shortDescription: 'Write and design a mini magazine.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/mini-magazine-creator.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 116, active: true },
    { name: 'My Review Column', slug: 'my-review-column', description: 'Write reviews of books, movies, products, or experiences.', shortDescription: 'Write opinion reviews.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/my-review-column.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 117, active: true },
    { name: 'Neighbourhood Interview Project', slug: 'neighbourhood-interview', description: 'Interview community members, practise active listening, and present their stories.', shortDescription: 'Interview people in your community.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/neighbourhood-interview.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 118, active: true },
    { name: 'Trail Guide Creator', slug: 'trail-guide-creator', description: 'Create a written guide to a local trail or walking path.', shortDescription: 'Write a trail guide.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/trail-guide-creator.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 119, active: true },

    // === ENTREPRENEURSHIP - New guides (sortOrder 120-129) ===
    { name: 'Brand Builder', slug: 'brand-builder', description: 'Build a brand identity from scratch: name, logo, personality, and values.', shortDescription: 'Build a brand from scratch.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/brand-builder.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 120, active: true },
    { name: 'Business Failure Lab', slug: 'business-failure-lab', description: 'Analyse real business failures, learn from mistakes, and build resilience.', shortDescription: 'Learn from real business failures.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/business-failure-lab.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 121, active: true },
    { name: 'Community Service Business', slug: 'community-service-business', description: 'Design and launch a service-based business with a social mission.', shortDescription: 'Build a business that helps your community.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/community-service-business.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 122, active: true },
    { name: 'Customer Discovery Challenge', slug: 'customer-discovery', description: 'Conduct real customer interviews, gather feedback, and refine a business idea.', shortDescription: 'Interview real customers.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/customer-discovery.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 123, active: true },
    { name: 'Investor Pitch Portfolio', slug: 'investor-pitch', description: 'Create a compelling investor pitch with financial reasoning and risk assessment.', shortDescription: 'Build an investor pitch.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/investor-pitch.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 124, active: true },
    { name: 'Marketing Campaign Creator', slug: 'marketing-campaign', description: 'Design and execute a marketing campaign to reach a real audience.', shortDescription: 'Create a marketing campaign.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/marketing-campaign.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 125, active: true },
    { name: 'Pricing Experiment', slug: 'pricing-experiment', description: 'Test different pricing strategies and make data-informed decisions.', shortDescription: 'Experiment with pricing strategies.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/pricing-experiment.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 126, active: true },
    { name: 'Product Design Lab', slug: 'product-design-lab', description: 'Use design thinking to create a product that solves a real problem.', shortDescription: 'Design a product from scratch.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/product-design-lab.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 127, active: true },
    { name: 'Supply Chain Detective', slug: 'supply-chain-detective', description: 'Trace a product\u2019s journey from source to consumer and understand global systems.', shortDescription: 'Investigate real supply chains.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/supply-chain-detective.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 128, active: true },
    { name: 'The Shark Tank Pitch', slug: 'shark-tank-pitch', description: 'Develop and deliver a high-stakes business pitch with financial thinking.', shortDescription: 'Pitch a business idea Shark Tank style.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/shark-tank-pitch.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 129, active: true },

    // === PLANNING & PROBLEM-SOLVING - New guides (sortOrder 130-139) ===
    { name: 'Emergency Ready Challenge', slug: 'emergency-ready', description: 'Think clearly under pressure and build confidence handling the unexpected.', shortDescription: 'Emergency preparedness challenges.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/emergency-ready.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 130, active: true },
    { name: 'Everyday Redesign Challenge', slug: 'everyday-redesign', description: 'Examine everyday objects and systems, then redesign them for better function.', shortDescription: 'Redesign everyday objects.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/everyday-redesign.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 131, active: true },
    { name: 'Fix-It Detective', slug: 'fix-it-detective', description: 'Diagnose and fix real household problems using logic and resourcefulness.', shortDescription: 'Fix real household problems.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/fix-it-detective.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 132, active: true },
    { name: 'Neighbourhood Problem Spotter', slug: 'neighbourhood-problem-spotter', description: 'Observe your neighbourhood, spot real problems, and brainstorm solutions.', shortDescription: 'Spot and solve neighbourhood problems.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/neighbourhood-problem-spotter.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 133, active: true },
    { name: 'Outdoor Survival Planner', slug: 'outdoor-survival-planner', description: 'Plan outdoor expeditions, think through scenarios, and build survival skills.', shortDescription: 'Plan outdoor survival adventures.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/outdoor-survival-planner.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 134, active: true },
    { name: 'Pack Like a Pro', slug: 'pack-like-a-pro', description: 'Master strategic packing: priorities, weight, space, and logistics.', shortDescription: 'Strategic packing and planning.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/pack-like-a-pro.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 135, active: true },
    { name: 'Scavenger Hunt Designer', slug: 'scavenger-hunt-designer', description: 'Design, create, and test your own scavenger hunts for friends and family.', shortDescription: 'Design your own scavenger hunts.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/scavenger-hunt-designer.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 136, active: true },
    { name: 'The Swap Day Challenge', slug: 'swap-day-challenge', description: 'Plan and run a swap day where you take on someone else\u2019s role or responsibilities.', shortDescription: 'Swap roles for a day.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/swap-day-challenge.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 137, active: true },
    { name: 'The What-If Scenario Lab', slug: 'what-if-scenario-lab', description: 'Explore hypothetical scenarios, predict outcomes, and plan responses.', shortDescription: 'Explore what-if scenarios.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/what-if-scenario-lab.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8–14', sortOrder: 138, active: true },
    { name: 'What Would You Do? Decision Lab', slug: 'decision-lab', description: 'Work through real decision scenarios, weigh options, and justify choices.', shortDescription: 'Practise real-world decision-making.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/decision-lab.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 139, active: true },

    // === WORLDSCHOOLING (sortOrder 200-209) ===
    { name: 'Cultural Celebration Journal', slug: 'cultural-celebration-journal', description: 'Document festivals, holidays, and cultural celebrations through guided observation and reflection.', shortDescription: 'Document cultural celebrations through observation.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08fAkIBECpwGmmkgwZ26F', blobUrl: '', imageUrl: '/products/cultural-celebration-journal.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 200, active: true },
    { name: 'Currency & Market Math', slug: 'currency-market-math', description: 'Convert currencies, compare prices, and practise mental maths in real markets.', shortDescription: 'Currency and market maths in real markets.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08fAkIBECpwGmwUsCteF2', blobUrl: '', imageUrl: '/products/currency-market-math.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 201, active: true },
    { name: 'Everyday Life Comparison', slug: 'everyday-life-comparison', description: 'Compare daily life across cultures: transport, food, school, and play.', shortDescription: 'Compare everyday life across cultures.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08gAkIBECpwGmg1RJabLC', blobUrl: '', imageUrl: '/products/everyday-life-comparison.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 202, active: true },
    { name: 'Local Language Mission', slug: 'local-language-mission', description: 'Build confidence in a new language through real-world missions and challenges.', shortDescription: 'Real-world language missions.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08gAkIBECpwGmAQk4fwgK', blobUrl: '', imageUrl: '/products/local-language-mission.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 203, active: true },
    { name: 'Nature & Geography Field Study', slug: 'nature-geography-field-study', description: 'Observe local plants, wildlife, climate, and geography wherever you travel.', shortDescription: 'Field study of nature and geography.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08hAkIBECpwGmAdyMW1AM', blobUrl: '', imageUrl: '/products/nature-geography-field-study.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 204, active: true },
    { name: 'People & Stories Interview Project', slug: 'people-stories-interview', description: 'Interview locals and travellers, listen carefully, and record their stories.', shortDescription: 'Interview people and collect stories.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08iAkIBECpwGmwqkBXDHr', blobUrl: '', imageUrl: '/products/people-stories-interview.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 205, active: true },
    { name: 'Street Explorer Map Maker', slug: 'street-explorer-map-maker', description: 'Walk new neighbourhoods and create hand-drawn maps with landmarks and stories.', shortDescription: 'Hand-drawn maps of new neighbourhoods.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08iAkIBECpwGmS2qJguOh', blobUrl: '', imageUrl: '/products/street-explorer-map-maker.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 206, active: true },
    { name: 'Transport & Navigation Challenge', slug: 'transport-navigation-challenge', description: 'Read maps, decode local transport, and plan real routes in unfamiliar places.', shortDescription: 'Navigate transport in new places.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08jAkIBECpwGmI2C7uWqZ', blobUrl: '', imageUrl: '/products/transport-navigation-challenge.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 207, active: true },
    { name: 'Travel Reflection & Postcards', slug: 'travel-reflection-postcards', description: 'Capture travel memories through hand-made postcards and reflective writing.', shortDescription: 'Hand-made postcards and travel reflection.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08jAkIBECpwGmq10DEOLG', blobUrl: '', imageUrl: '/products/travel-reflection-postcards.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 208, active: true },
    { name: 'World Food Detective', slug: 'world-food-detective', description: 'Investigate local cuisine: identify ingredients, trace origins, and document tastes.', shortDescription: 'Investigate world cuisine.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TS08kAkIBECpwGmQeQ2dPds', blobUrl: '', imageUrl: '/products/world-food-detective.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 209, active: true },

    // === EMOTIONAL & SOCIAL SKILLS (sortOrder 220-231) ===
    { name: 'The Calm-Down Toolkit', slug: 'calm-down-toolkit', description: 'Build a real reset kit and a when-I\'m-flooded plan from household stuff. Test tools that actually settle the body.', shortDescription: 'Build a real calm-down toolkit and reset plan.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpeAkIBECpwGmsTn643dE', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Calm-Down%20Toolkit.pdf', imageUrl: '/products/calm-down-toolkit.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 220, active: true },
    { name: 'The Big Feelings Lab', slug: 'big-feelings-lab', description: 'Name a feeling, find where it sits in the body, rate its size, and watch it pass. Build a personal feelings map.', shortDescription: 'Name big feelings and map them in the body.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpfAkIBECpwGmOwJg9l88', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Big%20Feelings%20Lab.pdf', imageUrl: '/products/big-feelings-lab.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 221, active: true },
    { name: 'The Boredom Toolkit', slug: 'boredom-toolkit', description: 'Build the skill of handling boredom without a screen. Real toolkit, a no-screens stretch, and a log of what they made.', shortDescription: 'Help kids handle boredom without a screen.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpfAkIBECpwGm3oxNsgji', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Boredom%20Toolkit.pdf', imageUrl: '/products/boredom-toolkit.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 222, active: true },
    { name: 'The Disappointment Lab', slug: 'disappointment-lab', description: 'Sit through a small planned letdown, name the feeling, and track how long it takes to bounce back.', shortDescription: 'Build resilience by tracking recovery time.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpgAkIBECpwGmdBefEIXn', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Disappointment%20Lab.pdf', imageUrl: '/products/disappointment-lab.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 223, active: true },
    { name: 'The Comeback Journal', slug: 'comeback-journal', description: 'Take a real flop, break it down without spiraling, pull out the lesson, pick the next move. Build a comeback journal habit.', shortDescription: 'Process real flops and pick the next move.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZphAkIBECpwGmkbMH03LR', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Comeback%20Journal.pdf', imageUrl: '/products/comeback-journal.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9–14', sortOrder: 224, active: true },
    { name: 'The Hard Thing Challenge', slug: 'hard-thing-challenge', description: 'Pick one genuinely hard thing, commit to it for a stretch, log the messy middle, and cross the finish.', shortDescription: 'Pick a hard thing and finish it.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZphAkIBECpwGmehQbYZr2', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Hard%20Thing%20Challenge.pdf', imageUrl: '/products/hard-thing-challenge.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 225, active: true },
    { name: 'The Repair Conversation', slug: 'repair-conversation', description: 'Practise what to do after hurting someone: own it, skip excuses, ask what would help, follow through.', shortDescription: 'Own a mistake and repair the relationship.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpiAkIBECpwGmg1Xu67b3', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Repair%20Conversation.pdf', imageUrl: '/products/repair-conversation.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 226, active: true },
    { name: 'The Kindness Missions', slug: 'kindness-missions', description: 'Build and work through a deck of real-world kindness challenges that take effort and noticing.', shortDescription: 'A deck of real-world kindness missions.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpiAkIBECpwGmna3K79c3', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Kindness%20Missions.pdf', imageUrl: '/products/kindness-missions.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 227, active: true },
    { name: 'Reading the Room', slug: 'reading-the-room', description: 'Practise noticing what others feel before words. Scan a room, read body language, infer the backstory.', shortDescription: 'Read body language and scan a room.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpjAkIBECpwGmj3tD6ezs', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20Reading%20the%20Room.pdf', imageUrl: '/products/reading-the-room.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9–14', sortOrder: 228, active: true },
    { name: 'The Conflict Fix', slug: 'conflict-fix', description: 'A real script for fights with siblings or friends: cool down, say it without attacking, hear the other side, find the fix.', shortDescription: 'A real script for conflict resolution.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpjAkIBECpwGmhgx7Rtab', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Conflict%20Fix.pdf', imageUrl: '/products/conflict-fix.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 229, active: true },
    { name: 'The Solo Mission', slug: 'solo-mission', description: 'Take on age-right do-it-without-me challenges: order at a counter, call a place, run an errand.', shortDescription: 'Solo missions in the real world.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpkAkIBECpwGmxbgBC5hB', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Solo%20Mission.pdf', imageUrl: '/products/solo-mission.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 230, active: true },
    { name: 'The Worry Sorter', slug: 'worry-sorter', description: 'Sort spinning worries into can-control vs cannot-control. Plan the controllable, practise letting go of the rest.', shortDescription: 'Sort worries and plan the controllable.', priceCents: 599, compareAtPriceCents: null, stripePriceId: 'price_1TdZpkAkIBECpwGmGO1cFkPF', blobUrl: 'https://xkj3tzlgu6ylgllk.public.blob.vercel-storage.com/Emotional%20%26%20Social%20Skills%20-%20The%20Worry%20Sorter.pdf', imageUrl: '/products/worry-sorter.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 231, active: true },

    // === START HERE (sortOrder 90) ===
    { name: 'The Future-Ready Skills Map', slug: 'future-ready-skills-map', description: 'A 44-page parent guide to the 12 skill areas that matter most for kids ages 0-16+, organised into three age phases (Play, Build, Apply).', shortDescription: '44-page parent guide: 12 future-ready skill areas, ages 0-16+.', priceCents: 999, compareAtPriceCents: null, stripePriceId: 'price_1T9JSZAMzOBftCntfh73EgWC', blobUrl: '', imageUrl: '/products/future-ready-skills-map.jpg', category: 'start-here', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 0\u201316+', sortOrder: 90, active: true },

    // === FREE-GUIDE FULL VERSIONS (membership-only, stripePriceId '') ===
    { name: 'Square Foot Safari', slug: 'square-foot-safari', description: 'Mark off one small square of ground and study it like a field scientist: observe, dig into the layers, keep field notes, and return across seasons.', shortDescription: 'Outdoor STEM science: study one square of ground like a field scientist.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/square-foot-safari.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 27, active: true },
    { name: 'The $20 Snack Mission', slug: 'snack-mission', description: 'A real budget, a real store, and real trade-offs. Your child plans, tracks a running total, makes choices, and counts the change.', shortDescription: 'Real-world STEM maths: a real budget, a real store, real trade-offs.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/snack-mission.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 113, active: true },
    { name: 'Household Orchestra', slug: 'household-orchestra', description: 'Build a piece of music from five random household objects. Explore sounds, build a rhythm, shape a piece, and perform it.', shortDescription: 'Creativity: turn five household objects into real music.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/household-orchestra.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 41, active: true },
    { name: 'Three AIs, One Question', slug: 'three-ais-one-question', description: 'Ask the same question to three AI tools, compare the answers, and figure out where the AI is bluffing. Done together at the keyboard.', shortDescription: 'AI literacy: ask three AIs one question and catch the bluff.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/three-ais-one-question.jpg', category: 'ai-literacy', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 9\u201314', sortOrder: 81, active: true },
    { name: 'Complaint to Product', slug: 'complaint-to-product', description: 'Turn an everyday family annoyance into a real product idea: collect complaints, pick one, invent a fix, design it, and pitch it.', shortDescription: 'Entrepreneurship: turn an annoyance into a real product idea.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/complaint-to-product.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 8\u201314', sortOrder: 131, active: true },
    { name: 'The Two-Minute Story', slug: 'two-minute-story', description: 'Take a real moment from life and learn to tell it as a clear, gripping story in two minutes. Find the shape, cut it down, and tell it for real.', shortDescription: 'Communication: turn a real moment into a gripping two-minute story.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/two-minute-story.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 121, active: true },
    { name: 'Plan a Mini Adventure', slug: 'plan-a-mini-adventure', description: 'Plan a real two-hour family outing from start to finish, then lead the day. Choose it, work out the details, make the plan, and look back.', shortDescription: 'Planning: plan and lead a real two-hour family outing.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/plan-a-mini-adventure.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 144, active: true },

    // === DEBUNDLED SEASONAL-PACK ACTIVITIES ===
    { name: 'Decomposition Detective', slug: 'decomposition-detective', description: 'Build a jar of leaves and soil, watch nature break it down over weeks, meet the decomposers, and run a fair test.', shortDescription: 'Outdoor STEM science: build a decomposition jar and watch it break down.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/decomposition-detective.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 28, active: true },
    { name: 'Seed Travelers', slug: 'seed-travelers', description: 'Collect seeds and test how each one travels, by wind, water, animal, or gravity, then design the ultimate seed.', shortDescription: 'Outdoor STEM science: test how different seeds travel.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/seed-travelers.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 29, active: true },
    { name: 'Camouflage Challenge', slug: 'camouflage-challenge', description: 'Hide objects in plain sight, time the search, test backgrounds, and crack the real rules of camouflage.', shortDescription: 'Outdoor STEM science: crack the real rules of camouflage.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/camouflage-challenge.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 30, active: true },
    { name: 'Nature Data Tracker', slug: 'nature-data-tracker', description: 'Track daylight, temperature, or rain over weeks, find the pattern, chart it, and predict what comes next.', shortDescription: 'Real-world STEM maths: track nature data and predict the pattern.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/nature-data-tracker.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6\u201314', sortOrder: 114, active: true },

    // === NEW 10 (Jul 2026) ===
    { name: 'Grow It, Eat It', slug: 'grow-it-eat-it', description: 'Plant a fast-growing edible, tend it from seed to harvest, and eat what you grew.', shortDescription: 'Outdoor STEM science: grow a fast edible and eat it.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/grow-it-eat-it.jpg', category: 'outdoor-learning', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 31, active: true },
    { name: 'Kitchen Science Lab', slug: 'kitchen-science-lab', description: 'Run real chemistry and physics experiments with everyday kitchen ingredients, then design your own.', shortDescription: 'Kitchen STEM science: real experiments with everyday ingredients.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/kitchen-science-lab.jpg', category: 'creativity-maker', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 42, active: true },
    { name: 'The Probability Lab', slug: 'probability-lab', description: 'Build a carnival game, work out the odds, set a price and prize, and see why the house always wins.', shortDescription: 'Real-world STEM maths: build a game of chance and crack the odds.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/probability-lab.jpg', category: 'real-world-math', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 115, active: true },
    { name: 'Secret Code Lab', slug: 'secret-code-lab', description: 'Write and crack secret codes, break a cipher with no key, and build a coded treasure hunt.', shortDescription: 'STEM logic: write, crack, and break secret codes.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/secret-code-lab.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 145, active: true },
    { name: 'The Body Owner\'s Manual', slug: 'body-owners-manual', description: 'Run real self-experiments on your own body, from heart rate to reflexes, and compile a personal body manual.', shortDescription: 'STEM science: measure your own body and write its manual.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/body-owners-manual.jpg', category: 'planning-problem-solving', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 146, active: true },
    { name: 'Family History Detective', slug: 'family-history-detective', description: 'Interview an elder, build a family timeline and tree, and turn one memory into a story worth keeping.', shortDescription: 'Communication: interview an elder and save the family stories.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/family-history-detective.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 122, active: true },
    { name: 'Teach It to Learn It', slug: 'teach-it-to-learn-it', description: 'Master a skill by teaching it: break it down, plan a real lesson, and deliver it to a live student.', shortDescription: 'Communication: learn a skill deeply by teaching it for real.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/teach-it-to-learn-it.jpg', category: 'communication-writing', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 123, active: true },
    { name: 'Trade It Up', slug: 'trade-it-up', description: 'Trade one small object up through a chain of real swaps, learning negotiation and what things are really worth.', shortDescription: 'Entrepreneurship: trade a paperclip up, one swap at a time.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/trade-it-up.jpg', category: 'entrepreneurship', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 132, active: true },
    { name: 'Play the World', slug: 'play-the-world', description: 'Learn and play a real local game while travelling, and read what it reveals about the place.', shortDescription: 'Worldschooling: play the games local kids play, wherever you are.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/play-the-world.jpg', category: 'worldschooling', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 210, active: true },
    { name: 'Be a People Scientist', slug: 'people-scientist', description: 'Hypothesis-test human behaviour with kind little experiments, tally the results, and learn something true about people.', shortDescription: 'Social skills: run kind experiments and read how people work.', priceCents: 599, compareAtPriceCents: null, stripePriceId: '', blobUrl: '', imageUrl: '/products/people-scientist.jpg', category: 'emotional-social-skills', isBundle: false, bundleProductIds: null, activityCount: null, ageRange: 'Ages 6–14', sortOrder: 232, active: true },
  ];

  // Upsert all products (update existing, insert new)
  for (const product of productData) {
    await db.insert(products).values(product).onConflictDoUpdate({
      target: products.slug,
      set: {
        name: product.name,
        description: product.description,
        shortDescription: product.shortDescription,
        priceCents: product.priceCents,
        compareAtPriceCents: product.compareAtPriceCents,
        imageUrl: product.imageUrl,
        category: product.category,
        isBundle: product.isBundle,
        activityCount: product.activityCount,
        ageRange: product.ageRange,
        sortOrder: product.sortOrder,
        active: product.active,
      },
    });
    console.log(`  ✓ ${product.name}`);
  }

  console.log(`\nSeeded ${productData.length} products successfully!`);
  console.log('\nReminders:');
  console.log('  - Run `npm run stripe:sync` to create products in Stripe and get real price IDs');
  console.log('  - Update blobUrl values after uploading PDFs to Vercel Blob');
}

seed().catch((err) => {
  console.error('Seed error:', err);
  process.exit(1);
});
